### ISSUE TITLE
[ASK] Can I save asset files such as audio / video / zip / other html?

### ISSUE THREAD

**Issue by azkadev** [dart-lang/native#1002]
I'm planning to make a web program but I want to save it as an exe. Does this feature already exist/will it?

**Comment by dcharkes** [comment]
As of currently, the native_assets_cli can only be used for the native backends, not for the web backends.
And as of currently, the native_assets_cli can only be used for bundling dynamic libraries, not data assets.

Tracking issue for data assets:

* https://github.com/dart-lang/native/issues/154

Tracking issue for adding wasm/js assets, which will require us supporting this new system for the web backends:

* https://github.com/dart-lang/native/issues/988

As far as I'm aware `dart compile js` and `dart compile wasm` are not really meant to be used in isolation. Rather they are used by UI frameworks such as Flutter to build an application that has assets bundled. For now you could look at using Flutter and using it's asset system. https://docs.flutter.dev/ui/assets/assets-and-images
