### ISSUE TITLE
Locking is not required around method and field ID lookup

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#1005]
`accessors.getClass` doesn't need locking either, since it's not used in C-bindings.

**Comment by dcharkes** [comment]
Do we need to add some kind of checking somewhere that we don't accidentally introduce calls in the C bindings to stuff that should not be used from C bindings?

E.g. some macro in the header file and then we compile the C code in a different way in a CI step?

**Comment by HosseinYousefi** [comment]
> Do we need to add some kind of checking somewhere that we don't accidentally introduce calls in the C bindings to stuff that should not be used from C bindings?
> 
> E.g. some macro in the header file and then we compile the C code in a different way in a CI step?

For `FindClass`, it's no longer possible to call it in C as I remove them from `dartjni.h`. In general I think we'll remove the C-bindings in general. They're more complicated, less user-friendly and not tree-shakable.

**Comment by dcharkes** [comment]
> not tree-shakable.

That should change with native assets and a C linker maybe?

But, I'm not opposed to removing them if we don't gain anything from them.
