### ISSUE TITLE
Method renamer should include type names.

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1007]
When I tried to generate the `UIImage` bindings, the generated code shows some errors:
<img width="1049" alt="截屏2024-03-14 16 06 04" src="https://github.com/dart-lang/native/assets/24455689/8186b4ac-bf28-4ebf-af3c-04e53ba9e918">
The wrong code is generated as follow
```
....
  ffi.Pointer<CGImage> get CGImage {
    return _lib._objc_msgSend_1228(_id, _lib._sel_CGImage1);
  }
...
final class CGImage extends ffi.Opaque {}
...
```
Maybe the `CGImage` property should changed to `cgImage`?
https://developer.apple.com/documentation/coreimage/ciimage/1687603-cgimage

**Comment by liamappelbe** [comment]
Does it work if you manually edit the generated code to rename the getter?

I think we use separate renamers for types vs methods. If we made the method renamer aware of all the type names, then it would rename this getter to `CGImage1`.

**Comment by yanshouwang** [comment]
> Does it work if you manually edit the generated code to rename the getter?
> 
> I think we use separate renamers for types vs methods. If we made the method renamer aware of all the type names, then it would rename this getter to `CGImage1`.

Yes, I can fix this error manually, why don't use cgImage instead of CGImage?

**Comment by liamappelbe** [comment]
> Yes, I can fix this error manually

I'm not actually asking you to fix it manually. I just wanted to confirm that this fix would work before I implement it.

> why don't use cgImage instead of CGImage?

The renaming needs to be something that ffigen can do programmatically. Renaming `CGImage` to `cgImage` isn't something I can do automatically in ffigen (how would it know to make only the first 2 letters lower case?).
