### ISSUE TITLE
System not configured correctly: No tools configured on host 'macos_arm64' with target 'macos_arm64'.

### ISSUE THREAD

**Issue by TENX-S** [dart-lang/native#1014]
Hi, 
I was trying to run the [example](https://github.com/dart-lang/native/tree/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/native_assets_cli/example/native_add_app) in `native_assets_cli`, but an exception was thrown when I executed the following command:
```console
dart --enable-experiment=native-assets run
```

The exception:

```console
Unhandled exception:
System not configured correctly: No tools configured on host 'macos_arm64' with target 'macos_arm64'.
#0      CompilerResolver.resolveCompiler (package:native_toolchain_c/src/cbuilder/compiler_resolver.dart:56:5)
<asynchronous suspension>
#1      RunCBuilder.compiler (package:native_toolchain_c/src/cbuilder/run_cbuilder.dart:77:44)
<asynchronous suspension>
#2      RunCBuilder.run (package:native_toolchain_c/src/cbuilder/run_cbuilder.dart:105:23)
<asynchronous suspension>
#3      CBuilder.run (package:native_toolchain_c/src/cbuilder/cbuilder.dart:246:7)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_library/build.dart:19:5)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:93:3)
<asynchronous suspension>
#6      main (file:///Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_library/build.dart:10:3)
<asynchronous suspension>
Building native assets for package:native_add_library failed.
build.dart returned with exit code: 255.
To reproduce run:
/Users/ares/Developer/SDK/flutter/bin/cache/dart-sdk/bin/dart --packages=/Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_app/.dart_tool/package_config.json /Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_library/build.dart --config=/Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_app/.dart_tool/native_assets_builder/ad29cd722e1e854649c58a2ea3b94553/config.yaml
stderr:
Unhandled exception:
System not configured correctly: No tools configured on host 'macos_arm64' with target 'macos_arm64'.
#0      CompilerResolver.resolveCompiler (package:native_toolchain_c/src/cbuilder/compiler_resolver.dart:56:5)
<asynchronous suspension>
#1      RunCBuilder.compiler (package:native_toolchain_c/src/cbuilder/run_cbuilder.dart:77:44)
<asynchronous suspension>
#2      RunCBuilder.run (package:native_toolchain_c/src/cbuilder/run_cbuilder.dart:105:23)
<asynchronous suspension>
#3      CBuilder.run (package:native_toolchain_c/src/cbuilder/cbuilder.dart:246:7)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_library/build.dart:19:5)
<asynchronous suspension>
#5      build (package:native_assets_cli/src/api/build.dart:93:3)
<asynchronous suspension>
#6      main (file:///Users/ares/Developer/Projects/native/pkgs/native_assets_cli/example/native_add_library/build.dart:10:3)
<asynchronous suspension>

stdout:
No compiler set in BuildConfig.cCompiler.cc.
Looking for Apple Clang on PATH.
Running `which clang`.
/opt/homebrew/opt/llvm/bin/clang
Found ToolInstance(Apple Clang, null, file:///opt/homebrew/Cellar/llvm/17.0.6_1/bin/clang-17).
Checking if ToolInstance(Apple Clang, null, file:///opt/homebrew/Cellar/llvm/17.0.6_1/bin/clang-17) satisfies CLI filter.
Running `/opt/homebrew/Cellar/llvm/17.0.6_1/bin/clang-17 --version`.
Homebrew clang version 17.0.6
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/homebrew/Cellar/llvm/17.0.6_1/bin
ToolInstance(Apple Clang, null, file:///opt/homebrew/Cellar/llvm/17.0.6_1/bin/clang-17) does not satisfy CLI filter.
No tools configured on host 'macos_arm64' with target 'macos_arm64'.

        
Error: Compiling native assets failed.
```

System: macOS 14.4 M3 Pro
```console
$ clang --version
Homebrew clang version 17.0.6
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by TENX-S** [comment]
Using the system bundled LLVM does eliminate the exception, but since the LLVM by Homebrew is recommended in [ffigen](https://github.com/dart-lang/native/blob/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/ffigen/README.md#macos), I'll leave this issue open in case someone finds it interesting.

**Comment by TENX-S** [comment]
> On what path is the system's built-in LLVM on your machine?
```console
$ clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dcharkes** [comment]
Hm, I believe this should work:

https://github.com/dart-lang/native/blob/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/native_toolchain_c/lib/src/native_toolchain/apple_clang.dart#L11-L23

The logic just looks at the `clang` on `PATH`, and then filters on whether `'Apple clang'` is party of the stdout when invoking with `clang --version`, which should be true.

Ah, I have reread your issue. Your problem is that it is not accepting the homebrew clang. That makes sense because non-Apple clang should be:

https://github.com/dart-lang/native/blob/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/native_toolchain_c/lib/src/native_toolchain/clang.dart#L11-L23

What we're missing is a fallback from Apple Clang to non-Apple clang on MacOS hosts.

https://github.com/dart-lang/native/blob/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/native_toolchain_c/lib/src/cbuilder/compiler_resolver.dart#L59-L68

However, I'm not entirely sure that a non-Apple Clang will work properly when trying to use MacOS or iOS system APIs, so we would need to investigate that. In other words, would the following options work with HomeBrew Clang?

https://github.com/dart-lang/native/blob/7e1e2b73a57507e6cb04b25e93228fc10ef689f8/pkgs/native_toolchain_c/lib/src/cbuilder/run_cbuilder.dart#L150-L153

**Comment by TENX-S** [comment]
For the sake of compatibility, I think it's fine to stick with the built-in Clang on macOS. In fact, I was not aware to install homebrew Clang until the [ffigen](https://github.com/dart-lang/native/blob/main/pkgs/ffigen/README.md#macos) requirements told me to do. Since we already got a built-in LLVM installed, is this requirement still necessary on macOS?

**Comment by dcharkes** [comment]
If I remember correctly, XCode might not contain a `libclang.dylib`. However, it seems that it does:

```
$ ls /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/
AppIntentsMetadataExtractor.framework	libswiftDemangle.dylib
SwiftSourceKitClientPlugin.framework	libtapi.dylib
SwiftSourceKitPlugin.framework		sourcekitd.framework
clang					sourcekitdInProc.framework
libIndexStore.dylib			swift
libLTO.dylib				swift-5.0
libSwiftDriver.dylib			swift-5.5
libclang.dylib				swift_static
libcodedirectory.dylib			tapi
```

@mannprerak2 @liamappelbe Would any of you happen to remember why we tell people to install llvm via homebrew? If we don't need it, we should fix our documentation!

**Comment by mannprerak2** [comment]
@dcharkes I'm not sure, maybe it was missed somehow. If we're sure this exists we should indeed update the documentation and the resolution paths.
