### ISSUE TITLE
Add Swift as a language in ffigen

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#1039]
We can't directly interop with Swift, but we're building tools that will allow Swift interop via ObjC. Ffigen should automatically invoke these tools.

**Comment by dcharkes** [comment]
Project proposal on: https://github.com/dart-lang/sdk/wiki/Dart-GSoC-2024-Project-Ideas#idea-swiftobjc-compatibility-tool

Possible names:

* `ffigen_swift` "It's FFIgen for Swift"
* `swiftgen` It's like FFIgen and JNIgen for Swift. (And it does happen to generate some swift code as well.)
