### ISSUE TITLE
Null check exceptions during json serialization during dry run

### ISSUE THREAD

**Issue by knopp** [dart-lang/native#1053]
CBuilder does not set architecture during dry run but it seems to be required during serialization:
```
Null check operator used on a null value
#0      NativeCodeAssetImpl.toJson (package:native_assets_cli/src/model/native_code_asset.dart:342:62)
#1      BuildOutputImpl.toJson (package:native_assets_cli/src/model/build_output.dart:96:46)
#2      BuildOutputImpl.toJsonString (package:native_assets_cli/src/model/build_output.dart:105:50)
#3      BuildOutputImpl.writeToFile (package:native_assets_cli/src/model/build_output.dart:155:24)
#4      build (package:native_assets_cli/src/api/build.dart:95:16)
<asynchronous suspension>
```

`DynamicLoadingBundledImpl` has permitted to have no file URI during dry run (which is good, as on Rust the location depends on architecture for example), but it fails during serialization:
```
Null check operator used on a null value
#0      DynamicLoadingBundledImpl.toJsonV1_0_0 (package:native_assets_cli/src/model/native_code_asset.dart:93:43)
#1      NativeCodeAssetImpl.toJson (package:native_assets_cli/src/model/native_code_asset.dart:341:21)
#2      BuildOutputImpl.toJson (package:native_assets_cli/src/model/build_output.dart:96:46)
#3      BuildOutputImpl.toJsonString (package:native_assets_cli/src/model/build_output.dart:105:50)
#4      BuildOutputImpl.writeToFile (package:native_assets_cli/src/model/build_output.dart:155:24)
#5      build (package:native_assets_cli/src/api/build.dart:95:16)
```

**Comment by dcharkes** [comment]
Thanks @knopp!

I didn't think of backwards compatibility with older SDKs when removing the architecture from dry runs.

The fix is to duplicate all assets and fill in all architectures for that OS on serialization, which is not very pretty but I believe the right thing to make it work.

**Comment by dcharkes** [comment]
Workaround: use the last dev build from Dart instead of stable.

Flutter workaround same after https://github.com/flutter/flutter/pull/145612 has landed.

**Comment by knopp** [comment]
I used `native_assets_cli` 0.5.2, which seems to be uploaded 2 days ago. There doesn't seem to be any dev version available? In anycase, things seem to be very much in flux right now, I'll retry once the dust settles a bit and https://github.com/flutter/flutter/pull/145612 lands.

**Comment by dcharkes** [comment]
You could try downgrading to 0.4.x

**Comment by knopp** [comment]
To make this clear, at this point I really don't care about backward compatibility (I'm actually curious if anyone currently does use native assets in production). I'm just trying to keep up the rust toolchain with latest changes in order to spot possible issues as soon as possible.
