### ISSUE TITLE
Primitives like fcntl and sem_open fail with Dart [Arm64] but Succeed with Dart [x86_64]

### ISSUE THREAD

**Issue by tsavo-at-pieces** [dart-lang/native#1062]
Hey there! 

I am working on implementing native_named_locks on MacOS, Linux, and Windows for the [DCLI](https://pub.dev/packages?q=dcli) package utilized by our Dart/Flutter App [pieces.app](pieces.app). 

I'm specifically working on all of our AOT Modules that power our GRPC infrastructure and as you can imagine the deprecation of `waitForEx` has myself and the other contributors hustling to help DCLI get v4 to beta/stable.

With that - I can't understate how critical this [native_named_locks](https://github.com/open-runtime/native_named_locks) implementation is for IPC synchronization! P.S. Don't judge me too hard on the implementation it's a work in progress (feedback appreciated) 😬 🙏

Some specifics: 

On MacOS and Linux I am leveraging [open](https://github.com/canonical/stdlibc.dart/blob/main/lib/src/fcntl.dart), [fcntl](https://github.com/canonical/stdlibc.dart/blob/main/lib/src/bsd/fcntl.dart), and [flock](https://github.com/canonical/stdlibc.dart/blob/main/lib/src/bsd/fcntl.dart) from the [stdlibc.dart](https://github.com/canonical/stdlibc.dart) package. 

It looks like there is a discrepancy between the two architectures when executing these native functions through FFI. 

Perhaps an encode/decode issue in [here somewhere](https://github.com/canonical/stdlibc.dart/blob/39eb446ed23eb29dc46feadba820d8be2eb851fd/lib/src/bsd/ffigen.dart#L1823C1-L1838C2):

```dart 

final class flock_t extends ffi.Struct {
  @ffi.LongLong()
  external int l_start;

  @ffi.LongLong()
  external int l_len;

  @ffi.Int()
  external int l_pid;

  @ffi.Short()
  external int l_type;

  @ffi.Short()
  external int l_whence;
}

```

or [here](https://github.com/canonical/stdlibc.dart/blob/39eb446ed23eb29dc46feadba820d8be2eb851fd/lib/src/std/ffigen.dart#L153C1-L156C1) / [here](https://github.com/canonical/stdlibc.dart/blob/39eb446ed23eb29dc46feadba820d8be2eb851fd/lib/src/std/fcntl.dart#L31C1-L40C56)

```dart 

  late final _fcntlPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('fcntl');
  late final _fcntl = _fcntlPtr.asFunction<int Function(int, int)>();


```

When running the unit tests for this package I get the following: 

<img width="994" alt="Screenshot 2024-03-27 at 10 58 19 PM" src="https://github.com/dart-lang/native/assets/102485237/2f596658-5328-4f8d-a1d5-28b3c420ca8d">

Highlighted in blue is the passing result of running the tests with the x86_64 SDK  followed by a failed test with the arm64 SDK.

This is also confirmed to be the case with GitHub Actions. 

Apple Silicon: 🛑 
Apple (Intel): ✅
Linux (Ubuntu + Intel): ✅ 

<img width="1451" alt="Screenshot 2024-03-27 at 11 19 15 PM" src="https://github.com/dart-lang/native/assets/102485237/3d365801-f6a0-43ec-8204-6d1668adf5cc">

Here are my Installed Dart Versions Per Each Architecture
```Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_x64"```
```Dart SDK version: 3.3.1 (stable) (Wed Mar 6 13:09:19 2024 +0000) on "macos_arm64"```

Any help would be greatly appreciated! Happy to try and make a fix just could use a few ideas and pointers (pun intended) 😅

Cheers, 
-Tsavo

**Comment by tsavo-at-pieces** [comment]
@mraleph Perhaps you have an idea about this? Major thanks in advance 🤝

I'm actually using the same techniques you did in [native_synchronization](https://github.com/dart-lang/native_synchronization/blob/main/lib/src/bindings/winapi.dart) on the [windows implementation](https://github.com/open-runtime/native_named_locks/blob/4c3bb11674886449c16f808ca17cd666cb2066e8/lib/src/bindings/windows.dart#L1C1-L213C29)

And attempted to implement named locks with semaphores as seen in [this (very dead code)](https://github.com/open-runtime/native_named_locks/blob/aot_monorepo_compat/lib/src/bindings/unix.dart) but had the same problem. 

sem_open kept failing on Dart arm64 but I realized it was an architecture thing when I had the idea to try it on x86_64 and then I realized it maybe wasn't all just user error 🫠

**Comment by dcharkes** [comment]
See https://github.com/canonical/stdlibc.dart/pull/114

**Comment by tsavo-at-pieces** [comment]
Amazing! 🙌

I'll make a pull request to stdlibc.dart!

**Comment by tsavo-at-pieces** [comment]
Worked like a charm with my forked version of stdlibc.dart! Going to have a great day tomorrow with windows 😅

I'm working on a MacOS system so it's going to be #pushandpray all day lol..

<img width="326" alt="Screenshot 2024-03-28 at 6 16 30 PM" src="https://github.com/dart-lang/native/assets/102485237/35e854e9-a743-48f9-aba7-392d9ba00ada">

Anyway... thank you so much for the help @dcharkes! Absolutely love dart & we're building some amazing product @[pieces.app](pieces.app) with the platform 🙌
