### ISSUE TITLE
[ffigen] Should we include `-Wno-nullability-completeness` compiler option by default?

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1073]
I can't run `flutter create --template=plugin_ffi my_package` and then `dart run ffigen --config ffigen.yaml` locally on MacOS without adding:

```yaml
compiler-opts:
  - '-Wno-nullability-completeness'
```

We can add this to the Flutter template, but it looks like we're littering this line across the all your `ffigen.yaml`s to make it work in the repository.
So maybe we should just add it by default if it can't do any harm.

**Comment by dcharkes** [comment]
wdyt @mannprerak2 @liamappelbe  ?

**Comment by mannprerak2** [comment]
Probably yeah, it would reduce a ton of warning logs.

I don't think this flag does anything other than skip warnings. So we probably don't need to increment the major version as well.
