### ISSUE TITLE
[jnigen] Output a list of dependencies & only rerun if dependencies changed

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1102]
Tracking issue for outputting all files (and directories) that if changed would require a rerun of JNIgen.

Similar feature for FFIgen:

* https://github.com/dart-lang/native/issues/1101

**Comment by HosseinYousefi** [comment]
Duplicate of #1009?

**Comment by dcharkes** [comment]
I am way ahead of myself!
