### ISSUE TITLE
[infra] NDK install fails on MacOS GitHub runner

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1115]
```
Run nttld/setup-ndk@6a7e9c5494a25c4842ca1011f710300132eacd94
  with:
    ndk-version: r[2](https://github.com/dart-lang/native/actions/runs/8906568850/job/24458937965?pr=1114#step:4:2)6b
    add-to-path: true
    link-to-sdk: false
    local-cache: false
  env:
    DART_HOME: /Users/runner/hostedtoolcache/dart/[3](https://github.com/dart-lang/native/actions/runs/8906568850/job/24458937965?pr=1114#step:4:3).3.4/arm64
    PUB_CACHE: /Users/runner/.pub-cache
Error: Error: Unsupported arch "arm6[4](https://github.com/dart-lang/native/actions/runs/8906568850/job/24458937965?pr=1114#step:4:4)"
```

I believe the MacOS bots were x64 before. It looks like they silently switched to arm64.

We run the arm64 MacOS bot less often because it wasn't free:

* https://github.com/dart-lang/native/pull/847

We should check if its free now.

Also, we probably want to keep running things on x64 MacOS.

**Comment by dcharkes** [comment]
Yep, the default is arm64 now: https://github.com/actions/runner-images/issues/9741

**Comment by dcharkes** [comment]
Tracking issue for the GitHub action we're using to install the NDK:

* https://github.com/nttld/setup-ndk/issues/548

However, an NDK should already be pre-installed on the bot:

* https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md

**Comment by dcharkes** [comment]
> Hello! As stated in the [table](https://github.com/actions/runner-images?tab=readme-ov-file#available-images) the only intel-based macOS-14 runner is macos-14-large ([doc](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners)). There are no plans to introduce macOS-14 intel standard runners as of now.

https://github.com/actions/runner-images/issues/9741#issuecomment-2075259811

@liamappelbe Maybe we should then change the weekly builder to be an x64 one? `macos-14-large`

**Comment by MulverineX** [comment]
It's fixed https://github.com/nttld/setup-ndk/pull/549

**Comment by dcharkes** [comment]
The GitHub bot already has an NDK pre-installed, so we're using that one now.

https://github.com/dart-lang/native/pull/1114/files#diff-67b78d3322afa689c9b62e854680e8087184f61dd7787f43ceb53f471eef6704

We can get back to installing one manually if we want a specific version of the SDK in the future.
