### ISSUE TITLE
Can't `structs.dependency-only: opaque` suppress "No definition found for declaration"?

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/native#1123]
This is probably more if a question than an issue.

**Reproduction steps:**
```bash
git clone https://github.com/google/webcrypto.dart
cd webcrypto.dart/
flutter pub get
flutter pub run ffigen --config=lib/src/third_party/boringssl/ffigen.yaml
```

I get a lot of warnings like:
```
[WARNING]: No definition found for declaration - (Cursor) spelling: evp_aead_st, kind: 2, kindSpelling: StructDecl, type: 105, typeSpelling: struct evp_aead_st, usr: c:@S@evp_aead_st
```

From what I can see these are [internal things](https://source.chromium.org/search?q=%22evp_aead_st%22&sq=&ss=chromium%2Fchromium%2Fsrc:third_party%2Fboringssl%2F).

There is a declaration `typedef struct evp_aead_st EVP_AEAD;` in a header file.
But the [definition](https://source.chromium.org/chromium/chromium/src/+/main:third_party/boringssl/src/crypto/fipsmodule/cipher/internal.h;l=77?q=%22evp_aead_st%22&ss=chromium%2Fchromium%2Fsrc:third_party%2Fboringssl%2F) is inside an `internal.h` file (which I'm guessing isn't included from `src/include/openssl/`.

I have [`structs.dependency-only: opaque`](https://github.com/google/webcrypto.dart/blob/137237cc792d7d047b1c02f5b8699259afd815e1/lib/src/third_party/boringssl/ffigen.yaml#L49-L53) in my `ffigen.yaml` file.

-----

Am I supposed to ignore this warning? Or is there a config option I'm missing?

Be ware it's obviously very plausible that I'm doing some fairly naive very wrong :rofl:

**Comment by dcharkes** [comment]
cc @mannprerak2

**Comment by mannprerak2** [comment]
Even for opaque type structs/unions, we do try to fetch the doc comment, hence the definition lookup.

But yes, we could do better even with this constraint. I've raised a PR for the same.
