### ISSUE TITLE
`jni` is incompatible with kotlin gradle plugin 1.6.20 or higher

### ISSUE THREAD

**Issue by btrautmann** [dart-lang/native#1135]
We're trying to use a package in our codebase that has a transitive dependency on `jni` via `cronet_http`. We are currently using version 7.4.2 of the Android Gradle Plugin, which is incompatible with the Kotlin version declared by `jni` (1.6.10).

We're wondering what we can do as a path forward. Would it make sense to open a PR bumping the AGP/Kotlin version used by `jni`, or would that have ripple effects? How is the upgrade process typically done?

**Links:**

Package we'd like to use: https://github.com/cfug/dio/tree/main/plugins/native_dio_adapter
`jni` declared Kotlin version: https://github.com/dart-lang/native/blob/main/pkgs/jni/android/build.gradle#L7
`jni` declared AGP version: https://github.com/dart-lang/native/blob/main/pkgs/jni/android/build.gradle#L15

**Comment by btrautmann** [comment]
Closing this as it's actually an incompatibility with the `kotlin-android-extensions` plugin causing this issue which has long been deprecated, so we'll need to migrate away from that to adopt the package. Sorry for any noise!

**Comment by tomfong** [comment]
I'm facing this issue as well. Any update?

**Comment by HosseinYousefi** [comment]
> I'm facing this issue as well. Any update?

The original poster closed this issue so no updates. 

Why are you facing an issue? Can you explain?

**Comment by tomfong** [comment]
> > I'm facing this issue as well. Any update?
> 
> The original poster closed this issue so no updates.
> 
> Why are you facing an issue? Can you explain?

Please refer to this issue:
https://github.com/dart-lang/http/issues/1300

**Comment by HosseinYousefi** [comment]
I see. Will update the dependency.

**Comment by HosseinYousefi** [comment]
It seems that I can do one better, removing the Kotlin dependency works as well.
