### ISSUE TITLE
ffigen ignores underlying enum type resulting in wrong struct size

### ISSUE THREAD

**Issue by MindStudioOfficial** [dart-lang/native#1185]
Since C++ 11 we can provide the type that is backing an enum like this:

```cpp
typedef log_level_e : uint8_t {
  info,
  success,
  warning,
  error
} log_level_e;
```

Then we can use this enum in a struct, where it will occupy the size of the specified type.

```cpp
typedef struct log_entry_t {
	log_level_e level; // sizeof(uint8_t)
	const char* message;
	size_t length;
} log_entry_t;
```

However ffigen will transform the struct and enum into the following:

```dart
final class log_entry_t extends ffi.Struct {
   @ffi.Int32()
   external int level;
   
   external ffi.Pointer<ffi.Char> message;

   @ffi.Size()
   external int length;
}
```

Where level now takes up more space in the dart version of the struct compared to the Cpp version.

> Note: ffigen only supports parsing C headers, not C++ headers.

I understand that this C++ feature is not supported by ffigen, but then it should at least give a warning or error when parsing a header that uses this feature. 
Currently there is no warning about this in the ffigen output and it just results in mangled data when using this struct.

**Comment by dcharkes** [comment]
cc @mannprerak2

**Comment by mannprerak2** [comment]
We currently generate an `Int32` for enum types everywhere.

We can use `clang_getEnumDeclIntegerType` to check the correct Integer type to use. It seems to range from `[ULong, UInt, Int, Long]` on my system depending on the values of the Enum constants.

Here are some outputs from libclang.

```
enum E0: uint16_t { E10 };
enum E1 { E11 };
enum E2 { E12=-1 };
enum E3 { E13=-1000000000000 };
enum E4 { E14=1000000000000 };
```

```
E0. (Type) spelling: uint16_t, kind: 119, kindSpelling: Elaborated
E1. (Type) spelling: unsigned int, kind: 9, kindSpelling: UInt
E2. (Type) spelling: int, kind: 17, kindSpelling: Int
E3. (Type) spelling: long, kind: 18, kindSpelling: Long
E4. (Type) spelling: unsigned long, kind: 10, kindSpelling: ULong
```

@dcharkes wdyt?
