### ISSUE TITLE
[native_assets_cli] `BuildConfig` `BuildOutput` hierarchy

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#12]
> Isn't this more general than only for native assets?

```
{
  'out_dir' :  ...,
  'native_assets' : {
    'c_compiler' : {
      'cc' : ...
      'cflags' : ...
      'ld' : ...,
    },
    'rustc' : {
      '...' : ...
    },
    'link_mode_preference' : 'static',
    ...
   },
}
```

I'd make this more hierarchical

_Originally posted by @mkustermann in https://github.com/dart-lang/native/pull/3#discussion_r1168767029_

**Comment by dcharkes** [comment]
This is an interesting idea.

In the discussions around `build.dart` earlier we discussed that dartdev/flutter_tools can start providing more config for different types of assets. I asked whether, `package:native_assets_cli` should not be `package:build_cli` instead and do all config [1]. That idea was rejected to keep the configs separate. But even if the config separate, it could indeed be useful to not pollute the namespace in the config file.

For build-output the same type of splitting of concerns yields some interesting questions.

* Single build output file?
  * The yaml from both packages `BuildOutput` would need to be merged into a single yaml.
    * This actually is kind of an argument to make a separate package `package:build_cli` that has the full `build.dart` supported spec.
  * would need to merge dependencies?
  * would need to decide on one time-stamp when the built was run
* Multiple output files
  * how do dartdev/flutter_tools then decide whether to run it again?
    * they would need to inspect all output files and check the dependencies and timestamps of all of them.

 doesn't really work because if you have both native assets and icons built by the same `built.dart` but using two different packages (`package:native_assets_cli` and `package:icons_cli`), they would need to merge their json/yaml.

[1] [internal meeting notes](https://docs.google.com/document/d/1Gt-mosQn7cUTIaSA7a2EwvaqMlYgVJfd5_CFWoU_5gc/edit?usp=sharing) _"`package:native_assets_cli` doesn’t have to be `package:build_cli`, for other types of assets we can have a different CLI spec."_

**Comment by dcharkes** [comment]
@natebosch @jakemac53 Maybe we should revisit if the CLI spec should be tied to Native Assets only. When think we might add other types of assets, for example icons, later.

**Comment by jakemac53** [comment]
Maybe consider just versioning this config file? Then you don't have to over-generalize it for now, but we would have the ability to later.

**Comment by dcharkes** [comment]
I believe nesting the `c_compiler` config is useful. With the Windows toolchain we also require a script that sets environment variables and the arguments to that script. That means we have 5 vars already related to the C compiler.

Nesting in `native_assets` could be useful because it would isolate the config for native assets from configs passed to other types of assets. However, it causes very long environment variables: `NATIVE_ASSETS__C_COMPILER__CC` vs `C_COMPILER__CC`. We're using [these environment variables](https://dart-review.googlesource.com/c/sdk/+/298580/14/pkg/test_runner/lib/src/configuration.dart) for example on the Dart CI where the c compiler is not installed in the default locations. Currently, the only key that would be under native_assets besides the c_compiler is `link_mode_preference`.
