### ISSUE TITLE
How to use dynamic array via ffi bindings?

### ISSUE THREAD

**Issue by ryanhoo** [dart-lang/native#1216]
Here is the libraw C struct define:
```
  typedef struct
  {
    enum LibRaw_image_formats type;
    ushort height, width, colors, bits;
    unsigned int data_size;
    unsigned char data[1];
  } libraw_processed_image_t;
```

And this is what's being generated via ffigen tool:
```
final class libraw_processed_image_t extends ffi.Struct {
  @ffi.Int32()
  external int type;

  @ushort()
  external int height;

  @ushort()
  external int width;

  @ushort()
  external int colors;

  @ushort()
  external int bits;

  @ffi.UnsignedInt()
  external int data_size;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.UnsignedChar> data;
}
```

I tried to do this:
```
//  ... load a raw photo ... test.arw

libraw_processed_image_t raw = rawImageData.ref;
ffi.Array<ffi.UnsignedChar> imageData = raw.data;
int size = raw.data_size; // size = 72721728
int firstByte = imageData[0]; // firstByte = 107
int secondByte = imageData[1]; // error

// turn the raw image data into a Uint8List and encode it as a jpeg...
```

`@ffi.Array.multi` limits the data to an array with size=1, if I try to access any data index greater than 0, there is an error:
```
open raw image session succeeded
dart:ffi                              Array._checkIndex
package:app/ffi/libraw/libraw.dart  RawImageSession.exportJpeg
test/raw_image_test.dart 16:13        main.<fn>

RangeError: Invalid value: Only valid value is 0: 1
```

I tried to hard code the test.arw image size 72721728 in `  @ffi.Array.multi([72721728])`, and everything works fine. 

But how to use dynamic array data in dart?

**Comment by dcharkes** [comment]
Variable length arrays are not supported yet:

* https://github.com/dart-lang/sdk/issues/52366

PR is out for review: https://dart-review.googlesource.com/c/sdk/+/371960

**Comment by ryanhoo** [comment]
Got it.
In my case, I set a max size for a raw photo (such as 200mb) and manually update the generated code from @ffi.Array.multi([1]) to @ffi.Array.multi([200*1024*1024]). Now it works fine.
