### ISSUE TITLE
JNI crashed with null object error with `LiveData<T>`

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1224]
I want to bind CameraX library with jnigen, but the app crashed when I call the `CameraController.getZoomState()` method with this error:
``` bash
JNI DETECTED ERROR IN APPLICATION: can't call float androidx.camera.core.ZoomState.getMinZoomRatio() on null object
```

, this method returns a `LiveData<ZoomState>` value which the `ZoomState` maybe null, but the generated JNI codes returns non-null type like this
``` dart
  static final _id_getZoomState = _class.instanceMethodId(
    r"getZoomState",
    r"()Landroidx/lifecycle/LiveData;",
  );

  static final _getZoomState = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>("globalEnv_CallObjectMethod")
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: public androidx.lifecycle.LiveData getZoomState()
  /// The returned object must be released after use, by calling the [release] method.
  LiveData<ZoomState> getZoomState() {
    return _getZoomState(
            reference.pointer, _id_getZoomState as jni.JMethodIDPtr)
        .object(const $LiveDataType($ZoomStateType()));
  }
```
If there someting I missed or this is a bug need to be fixed?

**Comment by HosseinYousefi** [comment]
Since technically every single Java object can be `null`, we don't generate all bindings as nullable (although we could – open an issue if you want to have that as an option!)

You have to check if your java object is null using `obj.isNull` instead.

**Comment by yanshouwang** [comment]
> Since technically every single Java object can be `null`, we don't generate all bindings as nullable (although we could – open an issue if you want to have that as an option!)
> 
> You have to check if your java object is null using `obj.isNull` instead.
> 
> If you're talking about Kotlin, then there is an issue for it: #1165

Thanks, I forgot this😅, I think this should be addressed when release the stable version.

Another thing is that I rememer that we don't need to release the JObject manually and all JObjects will be released automatically when  there is no reference, am I right?

**Comment by HosseinYousefi** [comment]
> Another thing is that I rememer that we don't need to release the JObject manually and all JObjects will be released automatically when there is no reference, am I right?

That's correct! Although you can, and sometimes you want to manually release.

The total number of java references your application can have is limited to ~50k and you might not want to rely on Dart GC to clean them up for you if you create a lot of them.

**Comment by yanshouwang** [comment]
> > Another thing is that I rememer that we don't need to release the JObject manually and all JObjects will be released automatically when there is no reference, am I right?
> 
> That's correct! Although you can, and sometimes you want to manually release.
> 
> The total number of java references your application can have is limited to ~50k and you might not want to rely on Dart GC to clean them up for you if you create a lot of them.

Thans for the explaination!
