### ISSUE TITLE
[native_assets_cli] Stop running link hooks in JIT mode.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1252]
We should stop running link hooks for JIT targets.

1. The hooks can't do anything meaningful over build hooks due to not having treeshaking info (https://github.com/dart-lang/native/issues/153).
2. Their "map-reduce"-like behavior means that many assets will be touched on rebuilds (cold start JIT, hot reload, hot restart (https://github.com/dart-lang/native/issues/1207)).

The price to pay is that in JIT-mode, a build hook needs to do the linking. So likely, there'll be some shared logic between the build and link hooks in packages that have a link hook.

And we need an API for `BuildConfig` detailing if the link hooks will be run: `bool BuildConfig.hasLinkPhase`?

* [x] Add `BuildConfig` field.
* [x] Stop running link hooks in JIT mode (Dart and Flutter PRs).
* [x] Add proper documentation.

Thanks @mkustermann @mosuem @HosseinYousefi @liamappelbe! Please leave additional suggestions, thoughts, etc!

**Comment by mosuem** [comment]
Documentation/Messaging on this is important, as we don't want people wondering why their link hooks did or did not run, or even worse, why some assets are there/missing if compiling in JIT vs. AOT.
