### ISSUE TITLE
Is NSObject.addObserver supported?

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1327]
The [`NSObject.addObserver`](https://developer.apple.com/documentation/objectivec/nsobject/1412787-addobserver?language=objc) seems not be generated by the `objective_c` plugin.

How can I generate this with ffigen?

**Comment by liamappelbe** [comment]
Looks like that method is part of a category (akin to Dart's extension methods) called `NSKeyValueObserverRegistration`. I can add its header file to the entry points, then it'll be included.
