### ISSUE TITLE
test pkgs/native_assets_builder/test/build_runner/link_test.dart fails on MacOS

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1381]
The following fixes the test suite for MacOS:

```dart
  test('treeshaking assets using CLinker',
      timeout: longTimeout,
      skip: Platform.isMacOS || Platform.isWindows, () async {
```

@mosuem are we not running this test suite on the CI for MacOS?

**Comment by mosuem** [comment]
We shouldn't run it - or what do you mean?

**Comment by dcharkes** [comment]
> We shouldn't run it - or what do you mean?

Well the test simply fails in the link hook because it's only supported on Linux. And the test has no `skip` or early returns for other OSes. I don't suppose we should run it if it will simply fail?
