### ISSUE TITLE
[swift2objc] Filtering

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#1394]
Like ffigen, swift2objc should have config options that let the user choose which APIs they want to generate wrappers for. Real Apple APIs have so many classes and methods that it's not practical to generate everything.

The `Config` should have callbacks that the user can set which return whether a particular class/struct/method/property should be generated. By default we should exclude everything.

**Comment by liamappelbe** [comment]
It'd be nice if we can do #1358 first and then implement filtering as a transformer

**Comment by nikeokoronkwo** [comment]
@liamappelbe Issue can be closed?
