### ISSUE TITLE
[ffi] Convert allocators to use `@Native`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1401]
This would make them compatible with dart2wasm if that exports the right symbols:

```dart
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Int)>(symbol: 'malloc')
external ffi.Pointer<ffi.Void> _wasmAllocate(
  int size,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'free')
external void _wasmDeallocate(
  ffi.Pointer<ffi.Void> ptr,
);

class _WasmAllocator implements ffi.Allocator {
  @override
  ffi.Pointer<T> allocate<T extends ffi.NativeType>(
    int byteCount, {
    int? alignment,
  }) {
    return _wasmAllocate(byteCount).cast<T>();
  }

  @override
  void free(ffi.Pointer<ffi.NativeType> pointer) {
    _wasmDeallocate(pointer.cast());
  }
}

final calloc = _WasmAllocator();
```

Thanks @TheComputerM!

**Comment by sam-p-at-pieces** [comment]
@dcharkes Not sure exactly how this works but I'm running into a compilation issue when build for web with `flutter build web --wasm`:

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
../../../.pub-cache/hosted/pub.dev/ffi-2.1.3/lib/src/allocation.dart:24:22: Error: Argument to 'Native.addressOf' must be annotated with @Native.
    Native.addressOf(posixFree);
```

Flutter Doctor output: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources
