### ISSUE TITLE
[native_assets_builder] Build should fail if builder requests non-linked assets but `hook/build.dart` emits assets with linker

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/native#1409]

**Comment by dcharkes** [comment]
I thought we had an issue to track that we should add a validation step, but I can't find it.

There's a bunch of other things to verify:

* assetsForLinking should be empty if linking is not supported
* only output asset types that are supported by the embedder
* files mentioned in assets actually exist
* native code assets for bundling should have a supported linking type
* build hooks should only output assets in their own package namespace
