### ISSUE TITLE
[native_assets_cli] `BuildConfig` should contain `packageName`

### ISSUE THREAD

**Issue by j4qfrost** [dart-lang/native#142]
I have written a library that I am importing into a larger project via git and the asset being built is using something like '<repo name>-<some hash>' when it should just be using the package name. I understand that this https://github.com/dart-lang/native/blob/be4aaf7b849a64d67756c95b6270b9bfe47f3c7d/pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart#L473 works in tests since everything is local. Are native builds currently restricted to local directories? Is there a way to access the proper package name through BuildConfig's internal config?

**Comment by dcharkes** [comment]
Hi @j4qfrost!

I don't think I fully understand your question. Can you elaborate on your problem?

What do you mean with a non-local directory?

What you can do is do a git-checkout inside your `build.dart` script. The downside is that you'll do a new checkout for every target architecture.
(To aid with this, we could consider adding something like the path to `<root-package>/.dart_tool/<your-package>` so that things can be cached there. So if your package is "foo", and someone uses your package in bar "bar", you'd get access to the path "the/path/to/bar/.dart_tool/foo/", and you can cache the git checkout in there.)

**Comment by j4qfrost** [comment]
Sorry for the ambiguity, I think you do understand my problem. I didn't provide my full process. So I am able to create the .so file successfully by doing something like this 
```dart
/* If I don't use the last path segment then I get this error:
package:wireguard-linux-dart-882f1353c4531a2e4b5b25dcb06bcf465d82cf04` 
declares the following assets which do not start with 
`package:wireguard-linux-dart-882f1353c4531a2e4b5b25dcb06bcf465d82cf04/`: 
package:wireguard_linux/native/native_wireguard_library.dart  */
  final packageName = buildConfig.packageRoot.pathSegments.lastWhere((e) => e.isNotEmpty); 
  final cbuilder = CBuilder.library(
    name: packageName,
    assetId: 'package:$packageName/native/native_wireguard_library.dart',
    sources: [
      'src/wireguard.c',
    ],
    pic: Platform.isLinux,
  );
```
but because it is named using the last path segment instead of the package name, I don't think that the ffigen code is finding the .so file properly. A couple hours after posting I do have a possible workaround in mind. I'll hack it out and close the issue tonight hopefully.

**Comment by dcharkes** [comment]
Let me know what solution you come up with. 👍 
This package is still under development, so maybe we can learn something from your approach that should be added to this package (or to the examples in this repo).

**Comment by blaugold** [comment]
I think `native_assets_builder` should not assume that the directory that contains a package always ends in the name of the package. 

I'm working on a package with the name `libvips`, but the repository is named `dart_libvips` so during development the directory containing the package ends in `dart_libvips`. Once installed from pub.dev the assumption `native_assets_builder` currently makes holds.

For example, I'm running in the following error, when running `dart test`:

```
`package:dart_libvips` declares the following assets which do not start with `package:dart_libvips/`: package:libvips/src/bindings.dart.
Error: Compiling native assets failed.
```

**Comment by j4qfrost** [comment]
> I think `native_assets_builder` should not assume that the directory that contains a package always ends in the name of the package. 
> 
> I'm working on a package with the name `libvips`, but the repository is named `dart_libvips` so during development the directory containing the package ends in `dart_libvips`. Once installed from pub.dev the assumption `native_assets_builder` currently makes holds.
> 
> For example, I'm running in the following error, when running `dart test`:
> 
> ```
> `package:dart_libvips` declares the following assets which do not start with `package:dart_libvips/`: package:libvips/src/bindings.dart.
> Error: Compiling native assets failed.
> ```
> 

This is essentially the crux of the issue. The furthest I've gotten getting my project to work is manually changing the asset id in the output config after building the project. I've tried rewriting the config via the build.dart script for both the root and dependency but the change doesn't propagate up to the root project's .dart_tool/native_assets.yaml unless the build happens from cache.

I think the only way to get the proper package name is to read it from the package config. I'm not sure why path resolution is being used in the first place, I've never run into the situation where I'm building two different versions of the same dependency in the same project.

**Comment by dcharkes** [comment]
Thanks for reporting!

The `native_assets_cli` needs to have the package name in the `BuildConfig`. And then `native_assets_builder` needs to pass it in.

(The field needs to be required, and the package versions need to be bumped to 0.3. This will temporarily break the Dart SDK test on this repo. And this will require bumping the deps in the Flutter experiment.)
