### ISSUE TITLE
How to know the real type of sub instance with ffigen?

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1438]
I defined some subclasses in swift and generated the dart bindings through ffigen. But when I want to know the sub instance's type like this, the code will throw the `ArgumentError` exception which means the check is failed. How can I do this with ffi?

``` Swift
@objc public class VideoRecordEvent: NSObject {
}

@objc public class VideoRecordStartEvent: VideoRecordEvent {
}

@objc public class VideoRecordFinalizeEvent: VideoRecordEvent {
    @objc public let uri: String
    @objc public let error: Error?
    
    init(uri: String, error: Error?) {
        self.uri = uri
        self.error = error
    }
}
```

``` Dart
extension FFIVideoRecordEventX on ffi.VideoRecordEvent {
  VideoRecordEvent get dartValue {
    final ffiEvent = this;
    if (ffiEvent is ffi.VideoRecordStartEvent) {
      return VideoRecordStartEvent();
    }
    if (ffiEvent is ffi.VideoRecordFinalizeEvent) {
      final uri = Uri.file('${ffiEvent.uri}');
      final ffiError = ffiEvent.error;
      final error = ffiError == null
          ? null
          : VideoRecordError('${ffiError.localizedDescription}');
      return VideoRecordFinalizeEvent(
        uri: uri,
        error: error,
      );
    }
    throw ArgumentError.value(this);
  }
}
```

**Comment by liamappelbe** [comment]
There's a special `isInstance` method on all the codegenned classes for this. So instead of `if (ffiEvent is ffi.VideoRecordStartEvent) {` you can write `if (ffi.VideoRecordStartEvent.isInstance(ffiEvent)) {`.

**Comment by yanshouwang** [comment]
> There's a special `isInstance` method on all the codegenned classes for this. So instead of `if (ffiEvent is ffi.VideoRecordStartEvent) {` you can write `if (ffi.VideoRecordStartEvent.isInstance(ffiEvent)) {`.

Thanks, it works!
