### ISSUE TITLE
[ffigen] Some objects must be destroyed on the platform thread

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#1470]
Some ObjC objects can only be used from the platform thread. These objects should also only be destroyed from the platform thread.

We can move [our finalizer](https://github.com/dart-lang/native/blob/main/pkgs/objective_c/src/objective_c.c#L28) to the platform thread easily enough, but there's no way of detecting which classes this is necessary for. So there are two options:
1. Move all objc_release calls to the platform thread. This might have performance implications.
2. Add config options for this. This would be pretty inconvenient, and if a user didn't know about this feature, or forgot to opt-in one of their classes, they'd get confusing crashes during GC.

**Comment by dcharkes** [comment]
"The best API is no API."

So probably option 1, unless we can measure performance impacts.

If we can't do option 1, I'd like to refrain from option 2. Because that would create an asymmetry between `runOnPlatfromTread` which is in Dart code and an option in `ffigen.yaml`. But I suppose we can't really make it configurable from Dart?

**Comment by stuartmorgan** [comment]
> 1. Move all objc_release calls to the platform thread.

It couldn't be done for *all* calls. If I have a thread-hostile Obj-C object, and I create an instance of it on a thread other than the platform thread, then this would break things.

**Comment by liamappelbe** [comment]
> If I have a thread-hostile Obj-C object, and I create an instance of it on a thread other than the platform thread, then this would break things.

An object like that will already be broken under the current approach, since GC can run on a background thread. There's currently no guarantee about what thread a finalizer will be run on. Do you have any objects like that?

I guess the ideal solution would be to have some way of ensuring that the object is destroyed on the same thread it was created on. I'm not sure that's possible in general though. We can't even guarantee the creation thread still exists. We might be able to use `NativeCallable.listener` to send the release call to the *isolate* that created the object, but that's a very expensive solution and there's no guarantee that the isolate would be running on the same thread.

**Comment by stuartmorgan** [comment]
> Do you have any objects like that?

I don't need this for `video_player`, no. Having thread-hostile, non-UI objects on background threads is definitely a pattern that can exist in Obj-C though.

> There's currently no guarantee about what thread a finalizer will be run on.

That is definitely extremely bad for the common case of platform-thread-only objects. That means my current `video_player` has undefined behavior, for instance.

**Comment by liamappelbe** [comment]
I don't see a good way of solving the fully general version of this problem. So until we have a concrete use case where option 1 won't work, I'm inclined to send every release call to the platform thread (assuming this is ok from a performance perspective). We know that this thread exists, and there are existing ObjC constructs to send tasks to it.

If users have an object that is very thread-hostile, my current advice would be to manage its life-cycle in native code (maybe write a thread safe wrapper that can be used in Dart). Or I guess you could just create and interact with it using `runOnPlatformThread` and rely on option 1 to send the release call to the platform thread. My hunch is that while it's possible to have objects like that in ObjC, they're probably not that common in practice.
