### ISSUE TITLE
functions in ifdef is ignored when generate ffi bindings with ffigen.

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1484]
When generate bindings with ffigen, the following function is ignored. How can I fix tell the generator to generate this function?

``` c

#if LIBUSB_API_VERSION >= 0x01000107
uvc_error_t uvc_wrap(
    int sys_dev,
    uvc_context_t *context,
    uvc_device_handle_t **devh);
#endif

```

**Comment by dcharkes** [comment]
You can pass defines with `compiler-opts` with `-D<macroname>=<value>`.

**Comment by yanshouwang** [comment]
> You can pass defines with `compiler-opts` with `-D<macroname>=<value>`.

Thanks, works like a charm!
