### ISSUE TITLE
[ffigen] Use Apple's libclang and update doc

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#1486]
>> @mannprerak2 @liamappelbe Would any of you happen to remember why we tell people to install llvm via homebrew? If we don't need it, we should fix our documentation!
>
> @dcharkes I'm not sure, maybe it was missed somehow. If we're sure this exists we should indeed update the documentation and the resolution paths.

_Originally posted by @mannprerak2 in https://github.com/dart-lang/native/issues/1014#issuecomment-2006382085_

@liamappelbe You're working with FFIgen and Apple's clang a lot, could you take a look at this?

**Comment by liamappelbe** [comment]
People should only be using xcode's clang. I updated the docs a while ago to capture this: https://github.com/dart-lang/native/pull/1081. Is there something else that needs doing?

**Comment by dcharkes** [comment]
Probably not, I just went through open issues and thought this might not yet have been addressed.
