### ISSUE TITLE
`Could NOT find Java` on Linux when using JNI on Adroid.

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#1488]
I used jnigen to implement plugin APIs on Android, but this will cause a CMake error when build the example project on Linux, how can I prevent this error when only use JNI on Android?

``` Shell
CMake Error at /snap/flutter/145/usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAR_EXECUTABLE
  Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE)
Call Stack (most recent call first):
  /snap/flutter/145/usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /snap/flutter/145/usr/share/cmake-3.16/Modules/FindJava.cmake:332 (find_package_handle_standard_args)
  flutter/ephemeral/.plugin_symlinks/jni/src/CMakeLists.txt:31 (find_package)
Error: Unable to generate build files
```

**Comment by yanshouwang** [comment]
I can solve this by add java to PATH. But it's will be better if we can just add jni dependency only on Android platform.

**Comment by HosseinYousefi** [comment]
> I can solve this by add java to PATH. But it's will be better if we can just add jni dependency only on Android platform.

I don't know a way to conditionally specify the platforms to support for a plugin.

**Comment by yanshouwang** [comment]
I think this is an issue related to Flutter, closed here.
