### ISSUE TITLE
[jnigen] Enable "listener" callbacks

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#1568]
Continuing in the path to get "interface implementation" feature out of experimental in JNIgen. 

JNIgen currently generates an `implement` factory on interface types like so:

```dart
abstract interface class $RunnableImpl {
  factory $RunnableImpl({
    required void Function() run,
  }) = _$RunnableImpl;

  void run();
}

class _$RunnableImpl implements $RunnableImpl {
  _$RunnableImpl({
    required void Function() run,
  }) : _run = run;

  final void Function() _run;

  void run() {
    return _run();
  }
}

class Runnable extends JObject {
  // Runnable has a factory named implement:
  factory Runnable.implement(
    $RunnableImpl $impl
  ) {
    // ...
  }
  // ...
}
```

If we pass `Runnable.implement(...)` to Java and it tries to call `.run` method, it will block until Dart actually runs it. However sometimes we don't have to block when the callback is intended to be a listener.

Of course, making a method into a "listener" is only possible to do if the return type of the said method is `void` (or maybe handling other cases like Java's `Future`).

We could add an enum parameter per (viable) method to communicate which methods have to be blocking vs. listener: `enum JCallMode { blocking, listener }`.

```dart
// Changed to mixin so `$mode`s can have a default value
abstract mixin class $RunnableImpl {
  factory $RunnableImpl({
    required void Function() run,
  }) = _$RunnableImpl;

  void run();
  JCallMode get run$mode => JCallMode.blocking;
}

class _$RunnableImpl implements $RunnableImpl {
  _$RunnableImpl({
    required void Function() run,
    JCallMode run$mode = JCallMode.blocking,
  })  : _run = run,
        _run$mode = run$mode;

  final JCallMode _run$mode;
  final void Function() _run;

  void run() {
    return _run();
  }

  JCallMode get run$mode => _run$mode;
}
```

Alternatively, a la [`NativeCallable`](https://api.dart.dev/stable/3.5.3/dart-ffi/NativeCallable-class.html), we could create a `JCallable<T extends Function>` and instead of requiring a simple function, require a `JCallable`. Then `JCallable` can have two factories: `.listener`, and `.blocking`. 

The issue here is that a simple callback implementation will be quite verbose:

```dart
Runnable.implement($RunnableImpl(run: JCallable.blocking(() => print('hello'))));
```

And non-void returning methods cannot be `JCallable.listener` anyways so it's unnecessary in those cases. 

@liamappelbe @dcharkes @mkustermann @lrhn Which syntax do you prefer? Or maybe something different.

**Comment by lrhn** [comment]
Tricky. 
My immediate comment is to drop the enum and use a `bool`.

Then a flag would be `run$block: false`,
and the member would be `bool get run$block;`.
My only quip is that a default of `true` is weird. But `run$noBlock: true` doesn't read well either.
Is there a positive word for not blocking? 
`run$lazy: true`? Or `late` or `async`?

**Comment by liamappelbe** [comment]
> My immediate comment is to drop the enum and use a `bool`.

Only issue with a bool is that we're adding more `NativeCallable` variants. [Temporary isolate callbacks](https://github.com/dart-lang/sdk/issues/54530) are in development.

Fwiw, the way ffigen handles this is by having 2 implementation methods, one which uses blocking callbacks for everything, and the other which uses listener callbacks for all the void methods. If the user wants more granularity than that, they can implement individual methods either as listeners or as blocking callbacks using the `ObjCProtocolMethod` fields on the protocol bindings. The implement methods themselves show how that's done:

```Dart
/// MyProtocol
abstract final class MyProtocol {
  /// Builds an object that implements the MyProtocol protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly.
  static objc.ObjCObjectBase implement(
      {int Function(SomeStruct)? optionalMethod_,
      void Function(int)? voidMethod_,
      required objc.NSString Function(objc.NSString, double)
          instanceMethod_withDouble_}) {
    final builder = objc.ObjCProtocolBuilder();
    MyProtocol.optionalMethod_.implement(builder, optionalMethod_);
    MyProtocol.voidMethod_.implement(builder, voidMethod_);
    MyProtocol.instanceMethod_withDouble_
        .implement(builder, instanceMethod_withDouble_);
    return builder.build();
  }

  /// Builds an object that implements the MyProtocol protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly. All
  /// methods that can be implemented as listeners will be.
  static objc.ObjCObjectBase implementAsListener(
      {int Function(SomeStruct)? optionalMethod_,
      void Function(int)? voidMethod_,
      required objc.NSString Function(objc.NSString, double)
          instanceMethod_withDouble_}) {
    final builder = objc.ObjCProtocolBuilder();
    MyProtocol.optionalMethod_.implement(builder, optionalMethod_);
    MyProtocol.voidMethod_.implementAsListener(builder, voidMethod_);
    MyProtocol.instanceMethod_withDouble_
        .implement(builder, instanceMethod_withDouble_);
    return builder.build();
  }

  static void addToBuilder(...
  static void addToBuilderAsListener(...

  /// optionalMethod:
  static final optionalMethod_ =
      objc.ObjCProtocolMethod<int Function(SomeStruct)>(...);

  /// voidMethod:
  static final voidMethod_ =
      objc.ObjCProtocolListenableMethod<void Function(int)>(...);

  /// instanceMethod:withDouble:
  static final instanceMethod_withDouble_ =
      objc.ObjCProtocolMethod<objc.NSString Function(objc.NSString, double)>(...);
}
```

**Comment by HosseinYousefi** [comment]
> Only issue with a bool is that we're adding more `NativeCallable` variants. [Temporary isolate callbacks](https://github.com/dart-lang/sdk/issues/54530) are in development.

If we add "`blocking`" and "`temporaryIsolate`" modes to `NativeCallable`, then we probably should just use them instead of normal Dart functions. I assume for example, `temporaryIsolate`  is going to have certain limitations, we want our users to get compiler errors/warnings if they ignore the lints. 

> `implementAsListener`

This is convenient. The slight issue I have with it is the fact that it implies that everything is a listener. Of course we know that the functions returning a value cannot be listeners but the user might not.

---

@lrhn What do you think about using `FutureOr<void>` as the return type of all the void methods instead? In the code we can check if `run is Future<void> Function()` or `void Function()` and decide if it's async/sync based on that. The nice thing is that there is no need for an extra argument per method.

**Comment by liamappelbe** [comment]
> If we add "`blocking`" and "`temporaryIsolate`" modes to `NativeCallable`, then we probably should just use them instead of normal Dart functions. I assume for example, `temporaryIsolate` is going to have certain limitations, we want our users to get compiler errors/warnings if they ignore the lints.

I considered doing this for ObjC, but there are some details that make this not quite work (eg the block's [invoke function pointer](https://clang.llvm.org/docs/Block-ABI-Apple.html#high-level) has a different signature to the user's function). Not sure if you'd have similar issues in jnigen.

**Comment by HosseinYousefi** [comment]
I've already implemented the `async` method way: #1596.

This is the check it uses to see if the `run` method is blocking or not:
```dart
           (($impl is _$MyRunnable &&
                ($impl as _$MyRunnable)._run is _$core.Future<void>
                    Function() &&
                ($impl as _$MyRunnable)._run is! _$core.Never Function()) ||
            ($impl.run is _$core.Future<void> Function() &&
                $impl.run is! _$core.Never Function()))
```
```dart
    // If the implementation is using the callback passing style, look at the
    // actual passed callback instead of the wrapper function. The wrapper is
    // always going to return `FutureOr<void>`.
    //
    // If the callback simply throws its return type will be `Never`. As any
    // function `R <F>` is a subtype of `Never <F>`, we should have a special
    // case for it. It's not possible to throw from a listener function, so
    // functions that only throw and hence have a `Never` return type, will be
    // considered to be sync.
```

---

Also I could have used `void` instead of `FutureOr<void>`. Maybe I'll even do that to make the autocompletion of implementing `$Foo` look nicer.

**Comment by HosseinYousefi** [comment]
Actually `void` seems to be a better choice overall as this is allowed:

```dart
FutureOr<void> Function() f = () { return Future<void>.delayed(Duration(seconds: 1)); };
```

but this isn't:

```dart
void Function() f = () { return Future<void>.delayed(Duration(seconds: 1)); };
```

While this is:

```dart
void Function() f = () async { return Future<void>.delayed(Duration(seconds: 1)); };
```

So it really makes it dependent on the existence of `async` keyword.

**Comment by orestesgaolin** [comment]
I wonder if this is what I'm looking for, but I'm looking for examples of how to invoke a callback from the native side back to Dart e.g. when some operation finishes.

E.g. for a class like this on the native side:

```java

public class FlutterPDFViewController {
    void onPageChanged(int page, int total) {
        // how to notify Dart about it
    }
}

Is there a way to somehow pass information back to Dart here?

**Comment by HosseinYousefi** [comment]
> Is there a way to somehow pass information back to Dart here?

`FlutterPDFViewController` can get a `Runnable` for instance. When constructing it from the Dart side you can pass in the runnable using `Runnable.implement($Runnable(run: ...))`. You can also implement it as listener: https://github.com/dart-lang/native/blob/main/pkgs/jnigen/doc/interface_implementation.md#implement-as-a-listener

**Comment by HosseinYousefi** [comment]
Looks good. If the individual methods don't need to be blocking, I suggest adding `[functionName]$async: true` for all functions like: `onPageChanged$async: true`.

**Comment by HosseinYousefi** [comment]
I also see that the `int` is generated as `int?` that's a bug which I'll fix (as primitives can't be null)! You can use `@NonNull` annotation to specify the nullability of the parameters in Java: 

```java
    void onError(@NonNull String error);
```
