### ISSUE TITLE
Error: 'dart:ffi' can't be imported when compiling to Wasm.

### ISSUE THREAD

**Issue by BirjuVachhani** [dart-lang/native#1576]
Unable to compile to Wasm because of `ffi` package. I don't use ffi directly but other packages I am using relies on it. I am assuming `ffi` package doesn't support wasm compilation yet!

```
Error: 'dart:ffi' can't be imported when compiling to Wasm.
                     import 'dart:ffi';

```

**Comment by mkustermann** [comment]
@BirjuVachhani Then either the package doesn't work on the web or the package uses conditional imports that need to be fixed. Please see the exact dependencies that led to the import of `dart:ffi` and see if any of them is relying on conditional imports. If so, then they may need to be fixed (e.g. most common issue: `import ... if (dart.library.html)` needs to be replaced with `import ... if (dart.library.js_interop) ...` - as `dart:html` is only available in dart2js but not dart2wasm - see https://github.com/dart-lang/sdk/issues/56358)

Adding FFI support on the web is a long standing issue that is tracked here: https://github.com/dart-lang/sdk/issues/46690
