### ISSUE TITLE
[ffigen] Failure on weekly arm64 bot

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/native#1617]
https://github.com/dart-lang/native/actions/runs/11087954105/job/30807210350

**Comment by dcharkes** [comment]
```
❌ /Users/runner/work/native/native/pkgs/ffigen/test/native_objc_test/isolate_test.dart: isolate Manual release across isolates (failed)
❌ /Users/runner/work/native/native/pkgs/ffigen/test/native_objc_test/isolate_test.dart: isolate Use after release and double release (failed)
❌ /Users/runner/work/native/native/pkgs/ffigen/test/large_integration_tests/large_objc_test.dart: Large ObjC integration test (failed)
```

Looks like the failures are related specifically to objc.

**Comment by liamappelbe** [comment]
There are fixes in https://github.com/dart-lang/native/pull/1616 and https://github.com/dart-lang/native/pull/1618 that should fix this. Not sure how to rerun the bot at head. Maybe we'll just wait until it reruns itself.
