### ISSUE TITLE
Unsupported operation: Cannot add to an unmodifiable list in build.dart scripts

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#168]
```
  Unsupported operation: Cannot add to an unmodifiable list
  dart:_internal                                                UnmodifiableListMixin.addAll
  package:native_toolchain_c/src/cbuilder/cbuilder.dart 276:45  CBuilder.run
  ===== asynchronous gap ===========================
  test/cbuilder/cbuilder_cross_android_test.dart 132:3          buildLib
  ===== asynchronous gap ===========================
  test/cbuilder/cbuilder_cross_android_test.dart 46:24          main.<fn>
```

@parlough it seems we're running into unmodifiable list errors being thrown in various places because the default values for arguments are now not modifiable. Could you please submit a PR to make the defaults modifiable again (and test it with unit tests).

I'm not sure why this was not caught by the CI earlier. 🙈

_Originally posted by @dcharkes in https://github.com/dart-lang/native/issues/161#issuecomment-1782646646_

Also failing on roll into Dart SDK: https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/pkg-linux-debug/18536/overview

```
Unsupported operation: Cannot add to an unmodifiable list
#0      UnmodifiableListMixin.addAll (dart:_internal/list.dart:129:5)
#1      CBuilder.run (package:native_toolchain_c/src/cbuilder/cbuilder.dart:276:45)
<asynchronous suspension>
#2      main (file:///b/s/w/ir/x/t/NRYGUQ/native_add/build.dart:21:3)
<asynchronous suspension>
```

**Comment by dcharkes** [comment]
I have retracted bad version https://pub.dev/packages/native_assets_cli/versions/0.3.1

Please bump the version to v0.3.2 when addressing this @parlough.

**Comment by parlough** [comment]
Sorry about that. I'm taking a look now.

**Comment by parlough** [comment]
The issue was not caught due to the packages depending on each through through pub rather than as path dependencies. It was the `native_toolchain_c` tests that failed which earlier on CI depended on a version of `native_assets_cli` during test.

For extra validation, it might make sense to run the tests for `native_toolchain_c` and `native_assets_builder` with a version of `native_assets_cli` from path, at least before a release. This will only work when there aren't intentional breaking changes though. I'm not sure the best way to do that though, or if it makes sense at all. I'll give it some more thought.

**Comment by dcharkes** [comment]
> The issue was not caught due to the packages depending on each through through pub rather than as path dependencies. It was the `native_toolchain_c` tests that failed which earlier on CI depended on a version of `native_assets_cli` during test.
> 
> For extra validation, it might make sense to run the tests for `native_toolchain_c` and `native_assets_builder` with a version of `native_assets_cli` from path, at least before a release. This will only work when there aren't intentional breaking changes though. I'm not sure the best way to do that though, or if it makes sense at all. I'll give it some more thought.

Ah yes, this is a known issue:

* https://github.com/dart-lang/native/issues/80
