### ISSUE TITLE
`native_assets_cli` 0.9 breaks `flutter_gpu_shaders` 0.1.3

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/native#1698]
`native_assets_cli` version 0.9 no longer requires `cli_config` as a dependency, which `flutter_gpu_shaders` 0.1.3 depends upon.

I'm wondering if this change is intentional, and thus I should open a PR to add `cli_config` to `flutter_gpu_shaders` as a required dependency?

Example error stack:

```console
FormatException: No value was provided for required key: out_dir_shared
#0      MapJsonUtils.get (package:native_assets_cli/src/json_utils.dart:50:7)
#1      MapJsonUtils.path (package:native_assets_cli/src/json_utils.dart:25:48)
#2      new HookConfig (package:native_assets_cli/src/config.dart:88:38)
#3      new BuildConfig (package:native_assets_cli/src/config.dart)
#4      build (package:native_assets_cli/src/api/build.dart:99:18)
#5      main (file:///Users/brettmorgan/.pub-cache/hosted/pub.dev/flutter_scene_importer-0.2.0-0/hook/build.dart:7:9)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

stdout:


../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error: Type 'BuildOutput' not found.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error: 'BuildOutput' isn't a type.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
Bad state: Generating kernel failed!
```

Also https://github.com/bdero/flutter_gpu_shaders/issues/3

**Comment by mkustermann** [comment]
> native_assets_cli version 0.9 no longer requires cli_config as a dependency
> ...
> I'm wondering if this change is intentional

Yes, it's intentional to no longer use `package:cli_config` in those packages.

> which flutter_gpu_shaders 0.1.3 depends upon.
> ...
> and thus I should open a PR to add cli_config to flutter_gpu_shaders as a required dependency?

If `package:flutter_gpu_shaders` doesn't use `package:cli_config`, why should it get it as a required dependency?

> Example error stack:
```
../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error: Type 'BuildOutput' not found.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/flutter_gpu_shaders-0.1.3/lib/build.dart:86:14: Error: 'BuildOutput' isn't a type.
    required BuildOutput buildOutput,
             ^^^^^^^^^^^
Bad state: Generating kernel failed!
```
> 

The `0.9.0` has made some breaking changes to the (still experimental) package. See also my comment here https://github.com/bdero/flutter_gpu_shaders/issues/3#issuecomment-2456987663. It will require minor updates to the code.

**Comment by bdero** [comment]
Build hooks that don't link a library are failing again (against 0.9.0):

```
Unhandled exception:
FormatException: No value was provided for required key: out_dir_shared
#0      MapJsonUtils.get (package:native_assets_cli/src/json_utils.dart:50:7)
#1      MapJsonUtils.path (package:native_assets_cli/src/json_utils.dart:25:48)
#2      new HookConfig (package:native_assets_cli/src/config.dart:88:38)
#3      new BuildConfig (package:native_assets_cli/src/config.dart)
#4      build (package:native_assets_cli/src/api/build.dart:99:18)
#5      main (file:///Users/bdero/projects/flutter/apps/flutter_scene/hook/build.dart:7:9)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Building native assets for package:flutter_scene failed.
file:///Users/bdero/projects/flutter/apps/flutter_scene/hook/build.dart returned with exit code: 255.
```

**Comment by mkustermann** [comment]
> Build hooks that don't link a library are failing again (against 0.9.0):
>
> FormatException: No value was provided for required key: out_dir_shared

That's probably on me: It seems the `out_dir_shared` support wasn't included in the recent release, which is probably why you see this: Newer `flutter run/build` and `dart run/build` will provide this, but not in older versions.

The refactoring I did to the `BuildConfig` made us read this eagerly and mandate it. I've setup an SDK constraint to the most recent release, but it may not have had that support yet.

If strongly needed, I could make a patch release that makes this `out_dir_shared` optional (for now). Then some release later can make it mandatory. Though it's easy to workaround: Just stick with 0.8.0 for now. Once newer Dart & Flutter SDKs have rolled out with this support, upgrade to 0.9.0. Would that work for you?

**Comment by domesticmouse** [comment]
The way I usually handle this is I tell Dependabot to jump in a lake every time it sends me a PR that fails CI.

**Comment by mkustermann** [comment]
@domesticmouse @bdero Version `0.9.0` should work with flutter `main` / `master` branch.

**Comment by bdero** [comment]
> Version 0.9.0 should work with flutter main / master branch.

Unfortunately, it doesn't. Yesterday I was running it against 5a3fd44ae.

I temporarily fixed this by pinning flutter_gpu_shaders to < 0.9.0.

Let's re-open this bug please.

**Comment by mkustermann** [comment]
> Unfortunately, it doesn't. Yesterday I was running it against 5a3fd44ae.

Have you tried with https://github.com/flutter/flutter/commit/3a83e43ede5700dfe4ea92709fec2c2365cdef4f or afterwards?

**Comment by bdero** [comment]
That landed today, so nope. Trying it.

**Comment by bdero** [comment]
Yup, confirmed it works now. Thanks!

**Comment by reidbaker** [comment]
@mkustermann we are seeing some failures on cherry pick pr to the 3.27 stable. Is there is a fix that can be pulled into that branch?

**Comment by mkustermann** [comment]
@reidbaker Could you be more specific? Are you trying to cherry-pick my changes? If so: why? Do you have a link to failures?

**Comment by reidbaker** [comment]
I am following @bkonyi comment from https://github.com/flutter/flutter/issues/156962#issuecomment-2460925873
