### ISSUE TITLE
`NSDictionary.objectForKey_` at head does not allow a `null` return

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/native#1701]
https://github.com/dart-lang/native/blob/a3749d2686531ad98f9f631e7a0927338ac77626/pkgs/objective_c/lib/src/objective_c_bindings_generated.dart#L2421

But 3.0 does:
https://pub.dev/documentation/objective_c/latest/objective_c/NSDictionary/objectForKey_.html

(the 3.0 version is correct)

**Comment by liamappelbe** [comment]
We mess around with the nullabilty of certain methods to work around some inheritance issues. The visitor refactor might have introduced bugs in that logic.

**Comment by liamappelbe** [comment]
Culprit: https://github.com/dart-lang/native/pull/1681
