### ISSUE TITLE
Lookup for helper library libdartjni.so failed.

### ISSUE THREAD

**Issue by award-wq** [dart-lang/native#1703]
I want to call a Kotlin function from dart using jnigen generated bindings. There is no other native platform code besides this Kotlin class that I want to include and it is all in one flutter project/package. The project is the standard flutter counter example. I created the AndroidUtils kotlin class with just a small demo.
```kotlin
package com.example.jnigendemo

class AndroidUtils {
    fun callInKotlin() {
        print("Call from Kotlin!")
    }
}
```
After bindings generation I simply call the function using `AndroidUtils().callInKotlin()` from the default button onPressed callback in the default template. This results in the following error:
```
The following HelperNotFoundError was thrown while handling a gesture:
Lookup for helper library libdartjni.so failed.
Please ensure that `dartjni` shared library is built.
Provided jni:setup script can be used to build the shared library.
If the library is already built, ensure that the JVM libraries can be 
loaded from Dart.
```

This is my jnigen.yaml:
```yaml
android_sdk_config:
  add_gradle_deps: true

output:
  dart:
    path: lib/android_utils.dart
    structure: single_file

source_path:
  - 'android/app/src/main/kotlin'
classes:
  - 'com.example.jnigendemo.AndroidUtils'
```

I generated the respective dart file using `dart run jnigen --config jnigen.yaml` which completed without errors. While I've seen similar issues about this already, none of them could help me solve my problem. I couldn't find the mentioned `libdartjni.so` anywhere.

How can I resolve this issue?

This is my `flutter doctor --verbose` output:
```
[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.22631.4391], locale en-GB)
    • Flutter version 3.24.4 on channel stable at C:\Users\username\Sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (13 days ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Users\username\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Users\username\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] Connected device (5 available)
------ removed ------

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by award-wq** [comment]
Further trying to debug this issue I noticed that the jni plugin is not registered. Neither in the GeneratedPluginRegistrant nor in the .flutter-plugins file. The latter is missing completely

**Comment by HosseinYousefi** [comment]
This is a flutter project, right? What versions of jni and jnigen are you using?

**Comment by HosseinYousefi** [comment]
And you're running the project on an android emulator?

**Comment by award-wq** [comment]
No. I'm running it on a physical device. This one has Android 8.1

**Comment by HosseinYousefi** [comment]
There is a Kotlin example in the jnigen repository, does that run correctly? https://github.com/dart-lang/native/blob/main/pkgs/jnigen/example/kotlin_plugin/example/lib/main.dart

**Comment by award-wq** [comment]
Yes. The other projects do run correctly. I'm able to create completely new project and get it to work fine as well. But I would still be interested in why this issue occurred and how to resolve it, in case this comes up in a bigger project which I cant just recreate again.

**Comment by HosseinYousefi** [comment]
Maybe you can run `flutter clean` and retry. 

`package:jni`'s build.gradle will build `libdartjni.so`, this might be a bug with the Flutter build system if it doesn't.

**Comment by award-wq** [comment]
That didn't work

**Comment by HosseinYousefi** [comment]
Correct me if I'm wrong here. You can make a new project that is *exactly* the same as your previous project and it works, but the original one doesn't? 

I can't help you if you don't provide me with a reproducible example here.

**Comment by award-wq** [comment]
After I bit more of trying to figure out why this happened, I decided to close this issue. Sadly I cant provide you an example project at this point but it seems like a generation error of the android part of a flutter project. Creating a new project with the - apparently - exact same code worked fine.
If anybody else experiences this issue, maybe they can provide an example project.
