### ISSUE TITLE
Accessing flutter plugin (FlutterPlugin) using jnigen

### ISSUE THREAD

**Issue by award-wq** [dart-lang/native#1708]
I created a plugin similar to this:

```kotlin
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware

@Keep
public class MyPlugin: FlutterPlugin, ActivityAware {
 ...my custom implementation
}
```

And registering it in the MainActivity like this:
```kotlin
    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        flutterEngine.plugins.add(MyPlugin())
    }
```

Accessing `MyPlugin` from the generated jni bindings returns a new instance of the class that hasn't been initialized by the flutter engine. How can I implement a workflow that allows me to access always the same instance of `MyPlugin` using jnigen generated bindings that was added to the flutter engine plugins in `configureFlutterEngine`.

**Comment by HosseinYousefi** [comment]
You can have a static singleton of your plugin that you register and access it from Dart.

**Comment by award-wq** [comment]
Thanks for the tip! Is there a way to do it without a singleton? Just curious.

**Comment by HosseinYousefi** [comment]
You won't have multiple of the same plugin registered anyways so all solutions will be quite similar.
