### ISSUE TITLE
vswhere.exe doesn't find anything

### ISSUE THREAD

**Issue by Keithcat1** [dart-lang/native#1844]
## Setup
OS: Windows 11 (64-bit)
Dart version: 3.6.0
## Problem
Simply invoking vswhere.exe without any other options just prints the logo and exits, causing the build process to crash when it can't find the compiler.
Invoking it like this:
```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
```
Prints:
```
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
```
Which seems to be what the code is trying to retrieve anyway. I only have Visual Studio Build tools installed (not Visual Studio), maybe that's why it's failing?

**Comment by dcharkes** [comment]
Hi @Keithcat1!

Thanks for the report.

> I only have Visual Studio Build tools installed (not Visual Studio), maybe that's why it's failing?

That might be true. If the build tools do contain the compiler (`cl.exe`), we should be able to support that use case. 👍 

Would you be willing to supply a PR s that it works for the case when only the build tools are installed? Then I can double check if it also works with full MSVC installed.
