### ISSUE TITLE
[native_assets_cli] Improve documentation on asset paths

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#188]
The documentation on asset paths is not clear on what context these asset paths refer to.

* Relative and Absolute: the location of the file after `build.dart` has been run. These are modified by flutter_tools and dart_dev upon copying assets to the app bundle.
* System: the location of a dylib on the target device. These paths are copied as is to the kernel mapping.

We need some vocabulary to talk about these different phases.

Thanks @mkustermann for reporting!

**Comment by dcharkes** [comment]
Hi @andzsinszan, nice to meet you! Are you talking about assets from build hooks? Or assets from the pubspec in Flutter?

**Comment by andzsinszan** [comment]
Nice to meet you @dcharkes , 
Thanks for your great work, fascinating project, tons of contributions from you.

> assets from build hooks? Or assets from the pubspec in Flutter?

I use pubspec. But probably that is the problem?
Resource is declared in pubspec of the FFI plugin.

```
flutter:
  assets:
    - res/model.onnx
```
It is lands in the build dir. So far so good. 
```
./build/linux/x64/debug/bundle/data/flutter_assets/packages/ffi_mic/res/model.onnx
./build/flutter_assets/packages/ffi_mic/res/model.onnx
```

During dev (linux target) I can only load the model if I use an abs path. The model loading takes place in C, path is a  `const char*`. For the worse - wrt to asset bundles - the C code runs in an isolate. Currently I am out of ideas. I couldn't even google if an image can be loaded from C/FFI.

**Comment by dcharkes** [comment]
> Resource is declared in pubspec of the FFI plugin.

Yes, the assets reported by build hooks are not connected at all to the assets from the pubspec at this point.
Also, the build hooks cannot yet report data assets, only code assets.

The assets from a Flutter pubspec are only available to Dart code as bytes or strings, they are not available as a file path.

Most likely the data assets from the build hooks, once they are implemented, will also not be available as a file path. (They might be bundled inside a zip file in an app bundle and not actually be on disk.)

**Comment by dcharkes** [comment]
> Most likely the data assets from the build hooks, once they are implemented, will also not be available as a file path. (They might be bundled inside a zip file in an app bundle and not actually be on disk.)

I've written some ideas on if we could make the file paths for data assets from build hooks available in the future:

* https://github.com/dart-lang/sdk/issues/54003#issuecomment-2128761001

For your current setup, you probably need to read your asset bytes (https://docs.flutter.dev/ui/assets/assets-and-images#loading-assets) and then write them to a File manually (https://api.dart.dev/stable/3.4.1/dart-io/File/writeAsBytes.html) and pass the path of that file to your C function.

P.S. Feel free to open new issues instead of reviving closed ones.

**Comment by andzsinszan** [comment]
Hi @dcharkes , 

Many thank, you just saved me from hours of frustration.

> The assets from a Flutter pubspec are only available to Dart code as bytes or strings, they are not available as a file path.

Great clarification. Explicitly stating what _cannot_ be done is sometimes just as useful as the valid use cases.   

> read your asset bytes && write them to a File && pass the path of that file to your C 

Very clear, thank you, will try. 

> P.S. Feel free to open new issues instead of reviving closed ones.

Thanks, will do - though trying not to spam the issue tracker.

**Comment by andzsinszan** [comment]
Just a quick feedback - hopefully not seen as spam. 
Data asset loading **works as advertised**. 
Loaded model in main isolate, sent over worker isolate, passed to C as `const char*`.  Skipped the file writing - not much of a disk IO fan. The char-wise copy is ugly, but works.
```
final lstView = req.model.buffer.asUint8List();
final Pointer<Uint8> charStar = malloc<Uint8>(lstView.length);
for(var i =0; i < lstView.length; i++) {
  charStar[i] = lstView[i];
}
// void* char -> charStar.cast<Void>()
```
Thanks @dcharkes

**Comment by andzsinszan** [comment]
thanks, all set. 
I used this line below (adding length as arg):
```
charStar.asTypedList(lstView.length).setRange(0, lstView.length, lstView);
```
