### ISSUE TITLE
Has anybody built complex mixed c/c++ projects with native_assets_cli?

### ISSUE THREAD

**Issue by crasm** [dart-lang/native#194]
The [`example/native_add_library`](https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example/native_add_library) is simple, so I am having a hard time understanding how to do a compile with e.g. the complexity of a typical pre-existing Makefile.

Basically, how would one write a build script to compile a project that has a mix of `-std=c11` and `-std=c++11` object files, and then make the final linked dynamic library available?

There's [only one package so far on pub.dev that depends on `native_assets_cli`](https://pub.dev/packages?q=dependency%3Anative_assets_cli) and it's also got a pretty simple compile.

Any pointers or help appreciated.

- - - - -

Context: I'm writing [dart bindings for llama.cpp](https://github.com/crasm/ensemble_llama) and want to experiment with this approach before committing to a manual build step.

The basic compilation I'm trying to get functioning on Apple Silicon is like this:
```
#!/bin/sh
set -ex
cc="clang -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_METAL  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Werror=implicit-function-declaration -Wunreachable-code-break -Wunreachable-code-return -Wdouble-promotion -pthread"
cxx="clang -D_XOPEN_SOURCE=600 -D_DARWIN_C_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS -DGGML_USE_ACCELERATE -DACCELERATE_NEW_LAPACK -DACCELERATE_LAPACK_ILP64 -DGGML_USE_METAL  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wmissing-declarations -Wmissing-noreturn -pthread  -Wunreachable-code-break -Wunreachable-code-return -Wmissing-prototypes -Wextra-semi"

ldflags="-framework Accelerate -framework Foundation -framework Metal -framework MetalKit"

$cxx    -o llama.o          -c llama.cpp      #-I{ggml,-{alloc,backend,metal}}.h
$cc     -o ggml.o           -c ggml.c         #-I ggml.h
$cc     -o k_quants.o       -c k_quants.c     #-I k_quants.h
$cc     -o ggml-metal.o     -c ggml-metal.m   #-I ggml-metal.h
$cc     -o ggml-alloc.o     -c ggml-alloc.c   #-I{ggml,{,-alloc}}.h
$cc     -o ggml-backend.o   -c ggml-backend.c #-I ggml.h -I ggml-backend.h

$cxx -shared -o libllama.so llama.o ggml.o k_quants.o ggml-metal.o ggml-alloc.o ggml-backend.o $ldflags -lstdc++
```

**Comment by dcharkes** [comment]
> how to do a compile with e.g. the complexity of a typical pre-existing Makefile

I think there are two options here:

1. Invoke `make` from build.dart and fail the build if `make` is not available on the end-users' system prompting them to install `make`. We'd probably want to add make as a tool in in `native_toolchain_c`.
2. Unentangle your make script and rewrite it on top of `package:native_toolchain_c`. We'd probably need to extend the API of that package to be able to call compilation to object files and the linking step separately.

**Comment by crasm** [comment]
(2) is definitely the way to go for this project, thanks! I'll give that a try.

**Comment by crasm** [comment]
@dcharkes works like a charm! 

[ensemble_llama/build.dart](https://github.com/crasm/ensemble_llama/blob/51966cdb08f061415fbc4c11568a31bef19ea679/build.dart)
