### ISSUE TITLE
[ffigen] CI is broken

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#195]
https://github.com/dart-lang/native/actions/runs/6862460674/job/18660199651

It was green on the PR, but apparently not after merging. Could you please take a look @liamappelbe ?

**Comment by liamappelbe** [comment]
Hmmm. It also [succeeded on Devon's PR](https://github.com/dart-lang/native/actions/runs/6867904767), but then [failed again on post-submit](https://github.com/dart-lang/native/actions/runs/6869506337/job/18682692175).

The failures were also slightly different. In the first failure it failed in the analysis step, but in the second failure it failed during mac testing. Both failures were while generating bindings for `test/native_objc_test/inherited_instancetype_test.m`. Looks like ffigen is flaky for this input. I'll try to repro locally.

**Comment by liamappelbe** [comment]
1200 runs without any issues, so this probably isn't a user facing issue. There must be something different about the github CI environment that makes it flaky.

**Comment by dcharkes** [comment]
It also seems to succeed for me locally.

```
$ xcodebuild -version
Xcode 15.0.1
Build version 15A507
```

I think we can still go ahead and release 10.0.0 stable today. But we can't really land PRs with new features afterwards if we can't trust the CI to give us a signal.

**Comment by dcharkes** [comment]
> Hmmm. It also [succeeded on Devon's PR](https://github.com/dart-lang/native/actions/runs/6867904767), but then [failed again on post-submit](https://github.com/dart-lang/native/actions/runs/6869506337/job/18682692175).
> 
> The failures were also slightly different. In the first failure it failed in the analysis step, but in the second failure it failed during mac testing. Both failures were while generating bindings for `test/native_objc_test/inherited_instancetype_test.m`.

Right, so we have at least three types of runs:

* green
* succeeding in the analysis step but failing on the mac test step
* failing on the analysis step

The two steps are identical though `dart test/setup.dart`, so that means flakiness inside the same run. So it's not flakiness that it succeeds on one machine but fails on another.

Failures in either of the two steps are roughly after ~30 seconds. Success takes 5-7 minutes.

**Comment by dcharkes** [comment]
Version of Xcode on the bots:

```
Running setup.dart in /Users/runner/work/native/native/pkgs/ffigen/test/native_objc_test/

Xcode 14.2
Build version 14C18

/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
```

https://github.com/dart-lang/native/actions/runs/6875922468/job/18700493698?pr=201

**Comment by dcharkes** [comment]
All the latest runs of FFIgen have been green.

I'll go ahead and close this for now.
