### ISSUE TITLE
[objc]: Generated code should pass pub static analysis

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/native#229]
The code generated by the Objective-C ffigen does not pass the static analysis used by pub:
![image](https://user-images.githubusercontent.com/8851008/201207217-522d3e45-08c1-4e56-99c3-c6a1a7194ab7.png)

Which causes the number of pub points to be reduced for the package.

**Comment by liamappelbe** [comment]
This seems to be fixed now. The remaining analysis issue on the [score page](https://pub.dev/packages/cupertino_http/score) is to do with formatting.
