### ISSUE TITLE
Linux: llvm-path: add lib64 and/or adjust search

### ISSUE THREAD

**Issue by esotericpig** [dart-lang/native#363]
Using ffigen v3.0.0.

On Fedora, Arch, Red Hat, CentOS, etc., libclang.so is installed in these locations:
- /lib64/libclang.so
- /usr/lib64/libclang.so

So out of the box, ffigen doesn't work.

Intuitively, you'd think to do this:

```yaml
# try everything
llvm-path:
  - '/lib64'
  - '/lib64/'
  - '/lib64/libclang.so'
  - '/usr/lib64'
  - '/usr/lib64/'
  - '/usr/lib64/libclang.so'
```

Frustratingly, none of these work, and you have to start *googling*.

After searching for a while, I finally found issue dart-lang/native#347 which states that the `lib` directory is automatically added. (Not documented *well*, as the wording on [pub.dev](https://pub.dev/packages/ffigen) is not intuitve).

So, you either have to use a symlink, or you have to specify the other location (which uses the exact version):

```yaml
llvm-path:
  - '/usr/lib64/llvm6.0/'
```

IMHO, I think the following should happen:
1. Search with and without adding `lib`.
    - Auto-adding `lib` is not intuitive and not documented *well*, except in a closed issue on GitHub.
    - Continue to auto-add `lib` so as not to break current config files that rely on it.
2. Add `lib64` to the directories auto-searched/added.

Lastly, it forces a naming scheme, so you *must* have a `lib` directory. For example, you can't have `./my_llvm/libclang.so` but instead *must* have `./my_llvm/lib/libclang.so`, which seems a bit odd to me for just wanting to specify a simple, basic path.

If no changes will be made, at the very least, I suggest adding it to the error message.

Current error messages:

```
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
[SEVERE] : Couldn't find lib/libclang.so in specified locations.
```

So the last line is saying it's looking for `lib/libclang.so` (same as pub.dev), which is not intuitive to me that `lib` is being auto-added to all of my paths. Maybe could change the wording:

```
[SEVERE]: The paths specified in the 'llvm-path' key in the config file
          will all have 'lib' appended to the end of the paths!
          You cannot enter '/lib64/' and expect that it will be found.
          It will then modify the path to be '/lib64/lib/'
          ...(whatever else you can think of)...
```

Thanks

**Comment by mushroom2** [comment]
`sudo apt install clang` will helps you.
