### ISSUE TITLE
Merge ffigen into dart-lang/native

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#437]
The process of merging a (non-mono) repo into dart-lang/native can be found here: https://github.com/dart-lang/tools/pull/100. @liamappelbe could you follow these steps for the FFIgen repo and make a PR in the same style?

_Originally posted by @dcharkes in https://github.com/dart-lang/ffigen/issues/612#issuecomment-1788516342_

Filing a separate issue to track this.

**Comment by liamappelbe** [comment]
All issues have been transferred, and https://github.com/dart-lang/ffigen/ is archived
