### ISSUE TITLE
[Objective-C] Unable to run blocks in the main thread 

### ISSUE THREAD

**Issue by renancaraujo** [dart-lang/native#463]
[Project to illustrate/reproduce this problem is here](https://github.com/renancaraujo/ffi_objc_main_thread).

As of right now, the objc/swift interop docs mention:

> You can work around this limitation [running stuff on the main thread] by writing some Objective-C code that dispatches your call to the main thread. For more information, see the Objective-C dispatch documentation.

It turns out that doesn't work. I tried to run a Dart function in the main thread, as well as running a swift code in the main thread. None worked. 

He swift code:

```swift
 @objc public func dispatchToMainAsync(_ block: @escaping () -> Void) {
        print("Hello from Swift")
        if Thread.isMainThread {
            print("Already on main thread")
            block()
        } else {
            print("Dispatching to main thread in an async way!")
            DispatchQueue.main.async {
                block()
            }
        }
    }
```

The dart coding invoking the bindings:

```dart
final block = ObjCBlock21.fromFunction(dismainLib, mainThreadMain);
DispatchToMain.new1(dismainLib).dispatchToMainAsync_(block);

/// ...

void mainThreadMain() {
  print("Hello from main thread!");
}
```

Unfortunately, that does not work, the `mainThreadMain` dart code is never called. If i change the swift side to `DispatchQueue.main.sync`, the dart process hangs. 

---
It also doesnt work even if we change the swift function to run dart code. 

```swift
...
 DispatchQueue.main.async {
    print("Hello from main thread!") // never called
}
...
```

---

**Comment by liamappelbe** [comment]
PlatformIsolates are working in Flutter. The request to support this in the Dart VM is not planned.

**Comment by Zekfad** [comment]
@liamappelbe Won't this be effectively solved by recent shared data proposal's Executor?
