### ISSUE TITLE
Specify LLVM path through CLI / environment variable

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#486]
Currently it is possible to specify LLVM path through YAML file, but sometimes it's necessary to do this on single system, while leaving the default locations working for anyone who clones the code and runs `ffigen` on a standard system.

For example, I have LLVM installed via `scoop` which means it's not on default location. Same can happen with less common linux distributions.

It would be nice to be able to specify this through command line or environment variable. The latter will also work with scripts which import `package:ffigen`.

**Comment by wexder** [comment]
@dcharkes setting LLVM path with env vars is super useful on systems like Nixos where you can spawn dynamic shells with packages. I can open new issue for this, but this seems like correct place to continue discussion

**Comment by dcharkes** [comment]
@wexder I think a general solution would be to address https://github.com/dart-lang/native/issues/1199, that would enable overriding arbitrary configuration from the yaml via env vars.
