### ISSUE TITLE
Add documentation to make it easier for developers to use

### ISSUE THREAD

**Issue by mariamhas** [dart-lang/native#553]
Add more specific documentation regarding the features and how to best to leverage JNIgen within their Dart and Flutter applications. 

The documentation should include:
- example for interface implementation
- Add a more specific add to app example

**Comment by mariamhas** [comment]
we should include in our docs how someone could do manually set that the calls generated are async. from the 1P customer perspective... having this as a boolean would make it easier but for mvp we should alteast have a way for developers to do it manually.

**Comment by HosseinYousefi** [comment]
Closed in favor of https://github.com/dart-lang/native/issues/1526
