### ISSUE TITLE
Ensure interacting with Java works on background isolates on Android

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/native#556]
When spawning isolates via e.g. `Isolate.spawn()` or `Isolate.run()`, the VM is in charge of creating threads and running the code. If such code were to call into Java using `package:jnigen` generated bindings, the bindings may e.g. look up class names etc.

Such lookups, e.g. via `JNIEnv->FindClass` are implemented by consulting the current class loader. On the main isolate the class loader will find application classes just fine, but it's unclear if that would work on background isolates.

See [JNI tips](https://developer.android.com/training/articles/perf-jni):

"""
It's usually best to use Thread.start() to create any thread that needs to call in to Java code. Doing so will ensure that you have sufficient stack space, that you're in the correct ThreadGroup, and that you're using the **same ClassLoader as your Java code**. 
"""

We should test that this works properly from helper isolates (without warming up cached data structures in main isolate first)

**Comment by HosseinYousefi** [comment]
Might be the reason behind this flaky test: https://github.com/dart-lang/native/actions/runs/6942927610/job/18886965060

**Comment by HosseinYousefi** [comment]
We're not using `JNIEnv->FindClass` for finding classes on Android, instead we use a custom `load_class_platform` that does:

```c
#ifdef __ANDROID__
  jstring className = (*jniEnv)->NewStringUTF(jniEnv, name);
  *cls = (*jniEnv)->CallObjectMethod(jniEnv, jni->classLoader,
                                     jni->loadClassMethod, className);
  (*jniEnv)->DeleteLocalRef(jniEnv, className);
#else
  *cls = (*jniEnv)->FindClass(jniEnv, name);
#endif
```

On Android, `jni->classLoader` is populated by `JniPlugin extends FlutterPlugin`'s `onAttachedToEngine` to be `getClass().getClassLoader()`. 

The isolate tests also pass. Closing this.
