### ISSUE TITLE
Incorrect renaming when the method/field already has a numeric suffix

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#571]
For example, if we have three methods: `overloaded`, `overloaded` and `overloaded1`. The second `overloaded` gets converted to `overloaded1` but `overloaded1` stays the same.

**Comment by HosseinYousefi** [comment]
Multiple ways to solve this:

* First come first serve: `foo`, `foo`, `foo1` -> `foo`, `foo1`, `foo2`
  - Pro: Simplest.
  - Con: User would expect `foo1` to be `foo1` but it's not.
* First all the unique names, then all the non-unique ones: `foo`, `foo`, `foo1` -> `foo`, `foo2`, `foo1`
  - Pro: Less confusing `foo1` remains `foo1`.
  - Con: Users would expect all these to be overloadings of `foo`, but the only overloading is `foo2`.
* Use a separator: `foo`, `foo` ,`foo1` -> `foo`, `foo$1`, `foo1`.
  - Pro: Most clear. Anything with `$` is overloaded.
  - Con: Adds a symbol to all overloaded methods. Overloaded methods are used a lot, but methods that end with a number are rare.

@liamappelbe @dcharkes wdyt? What happens in ffigen? Maybe we should use the same technique.

**Comment by dcharkes** [comment]
The second option would require multiple traversals with visitors and saving such information somewhere. Could be done, but complicates things for users.

A separator is not a bad idea, it also signals the rename to the user.

**Comment by HosseinYousefi** [comment]
> A separator is not a bad idea, it also signals the rename to the user.

Another way: methods with numeric suffices get an extra `$` suffix.

`foo`, `foo`, `foo1`, `foo1` -> `foo`, `foo1`, `foo1$`, `foo1$1`

As methods ending with a number are rare in Java (as Java has operator overloading), it's both correct and not ugly in the happy path.

**Comment by liamappelbe** [comment]
In this case, ffigen's [`UniqueNamer`](https://github.com/dart-lang/native/blob/main/pkgs/ffigen/lib/src/code_generator/utils.dart) would do `foo`, `foo`, `foo1`, `foo1` -> `foo`, `foo1`, `foo11`, `foo12` 😆. It doesn't try to parse the numbers at the end of the name, it just adds an incrementing number to the end of whatever you give it, until it finds something not in its set.

**Comment by HosseinYousefi** [comment]
I think I like the last way the best. @liamappelbe Feel free to do the same for ffigen to be consistent.
