### ISSUE TITLE
Machine dependent mandatory parameters in config

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#581]
### Problem:
* Certain source code or JARs (such as, but not only, Android SDK) differ across machines.
* Also, it's not possible to override the individual elements of a list such as `source_path` from command line.

### Proposed solution:
Provide a very lightweight YAML syntax to provide a source / classpath parameter from command line.

__Example:__

```yaml
class_path:
  - "app/target/classes"
  - "${ANDROID_SDK}/android.jar"
```

From command line

```bash
dart run jnigen --config jnigen.yaml -P ANDROID_SDK=~/.android/platforms/android-28
```

This should allow us to get rid of currently very fragile android SDK detection heuristics.

__But I'm also open to improving android SDK detection. This is a more general, but also slightly verbose solution.__

### Implementation
* Regex search / replace should be sufficient.
* A bare `$` may be present in a path, but a `${` should be very much impossible.

#### Similar
Docker compose uses similar syntax in its YAML.

cc: @HosseinYousefi

@dcharkes if we want to implement this, will `package:config` be a more appropriate place?

**Comment by HosseinYousefi** [comment]
We're going to remove the YAML config in favor of Dart scripts calling the API.
