### ISSUE TITLE
General form for C binding functions

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#638]
This is an example of a C wrapper generated now:

```c
jmethodID _m_JsonToken__isScalarValue = NULL;
FFI_PLUGIN_EXPORT
JniResult JsonToken__isScalarValue(jobject self_) {
  load_env();
  load_class_global_ref(&_c_JsonToken, "com/fasterxml/jackson/core/JsonToken");
  if (_c_JsonToken == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_JsonToken, &_m_JsonToken__isScalarValue, "isScalarValue",
              "()Z");
  if (_m_JsonToken__isScalarValue == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  uint8_t _result =
      (*jniEnv)->CallBooleanMethod(jniEnv, self_, _m_JsonToken__isScalarValue);
  return (JniResult){.value = {.z = _result}, .exception = check_exception()};
}
```

This is quite large, for one method.

If we look at the JNI API, there are 7 forms of methods we are using.

```
Call<type>Method
Call<type>StaticMethod
Get<type>Field
Get<type>StaticField

Set<type>Field
Set<type>StaticField

NewObject
```

Each of these have some general form. For example each method calling `CallBooleanMethod` does the following.

* attach thread-local JNIEnv if not already
* load class into a global ref, if not already loaded
* load method ID, if not already loaded
* call the method

So if we parameterize these things into an imaginary function called `DoCallBooleanMethod`, the above binding becomes

```c
jmethodID _m_JsonToken__isScalarValue = NULL;
FFI_PLUGIN_EXPORT
JniResult JsonToken__isScalarValue(jobject self_) {
    DoCallBooleanMethod(
        &_c_JsonToken, // class ref
        "com/fasterxml/jackson/core/JsonToken", // class name
        &_m_JsonToken__isScalarValue, "isScalarValue", "()Z", // Method loading parameters
        ref,
        // next parameters....
}
```

It increased parameter count by 3, but I think for any modern varargs implementation in C that should not be a problem.

Same general form can be followed for other families of functions.

A nice side effect is that the generated bindings don't need helper functions from `dartjni.h` anymore, so we can move all the `static inline` hacks into `dartjni.c`.

@dcharkes @HosseinYousefi wdyt?

**Comment by HosseinYousefi** [comment]
Closing this now that we plan to remove the C-based bindings altogether.
