### ISSUE TITLE
mono repo directory structure

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#665]
We're using `pkgs/` for some mono repos:

* https://github.com/dart-lang/build
* https://github.com/dart-lang/shelf
* https://github.com/dart-lang/test
* https://github.com/dart-lang/tools

Note, not all mono repos are following this structure (yet?):

* `pkg/` (not `pkgs/`)
   * https://github.com/dart-lang/pub-dev
* top level folders
   * https://github.com/dart-lang/jnigen 
   * https://github.com/dart-lang/webdev

Further reading: https://pub.dev/packages/mono_repo

@devoncarew do we have a preferred layout?
Should we consider moving the packages in here into `pkgs/`?

**Comment by HosseinYousefi** [comment]
We already brought everything to dart-lang/native!
