### ISSUE TITLE
Incomplete sources parser

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#668]
The Android `sdkmanager` provides a way to get the sources along with SDK, which are presumably used by the IDE to provide documentation features.

(There's some fragmentation here. There's an `android.jar` which exists in gradle classpath, a JAR of source stubs, and SDK sources download option. I have found the last one to contain javadoc most reliably so far, so it may be worth parsing that.)

However these sources are broken. Eg: refer to classes which do not exist in the same bundle. (They might be generated from, eg: a protobuf schema during build).

Current source summarizer expects all required symbols to be properly resolved.

However, if Android Studio can make sense of these sources, it has some parser which gracefully handles incomplete sources.

We should investigate the possibility of having a parser option which does handle missing symbols gracefully, either by skipping the enclosing symbol or assigning some default to unresolved symbol.

Here are some parsing libraries I found at - https://mvnrepository.com/open-source/java-compilers-and-parsers.

* JavaParser + it's symbol solver library.

* QDox

* Eclipse ECJ

Would be great if any of them supports parsing incomplete sources and support fairly recent language level (11). The new parser can make use of most of existing summarizer infrastructure.

**Comment by HosseinYousefi** [comment]
Decided to parse the html of javadocs instead. #1079.
