### ISSUE TITLE
[Docs] Please document the differences between, and when to use JNI, over `MethodChannel`s

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/native#677]
hello,

Im a flutter beginner, and currently working with flutter's `MethodChannel`s, to communicate with respective platforms, but found it quite un-reliable. I read about JNI sometime ago,

But I:
- Neither know where to start, and 
- Should I even consider JNI, also 
- In which all situations, JNI should be preferred over `MethodChannel`s,

I found [this](https://stackoverflow.com/questions/74222966/how-flutter-methodchannel-works-and-how-it-is-different-from-interop), helpful, but not much,

thanks

**Comment by josxha** [comment]
Leaving this awesome video by the jnigen team at the Google IO 2023 here because I think it fits well in this issue. It's a great resource and very well explained: https://www.youtube.com/watch?v=ZWp2FJ2TuJs
