### ISSUE TITLE
Investigate getting rid of manual YAML handling

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#688]
Investigate the possiblity to use [checked_yaml](https://pub.dev/packages/checked_yaml) or a similiar package to deserialize YAML into `Config`.

Something like

* Get `YamlMap` using `package:yaml`
* Apply overrides from command line to `YamlMap`
* Deserialize YAML using `json_serializable` and `checked_yaml`
* Run additional checks on `Config` struct, which can't be expressed using type constraints. This can be put in config constructor, so that it will be run when called from factory method generated by `json_serializable` as well as from the programmatic API.

**Comment by HosseinYousefi** [comment]
Decided to remove yaml completely in the future versions.
