### ISSUE TITLE
infra / workflow setup question

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/native#70]
I see that you have one workflow file for three packages: https://github.com/dart-lang/native/blob/main/.github/workflows/dart.yaml.

Are you happy with this setup? It's also possible (w/o much real duplication) to have a workflow file per packages, and to have those workflows only trigger when files in each individual package change. See https://github.com/dart-lang/tools/tree/main/.github/workflows for an example.

**Comment by devoncarew** [comment]
cc @dcharkes

**Comment by dcharkes** [comment]
Yes, currently the packages are all path dependencies on each other, that means I might break a dependent package when doing changes.

Once we start publishing these packages and replacing the path dependencies with published dependencies, then we should probably switch to only testing the packages that were actually touched.

(Slightly off topic: We'll likely break coverage again when changing the CI jobs. @HosseinYousefi mentioned we could possibly switch from coveralls to codecov, it has a better UI and is maybe easier to setup/maintain.)
