### ISSUE TITLE
Publish a v0.1 for all three packages

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#71]
In order to make a pull request for flutter_tools, the packages on this repo need to be published.

Reference:

* https://github.com/flutter/flutter/issues/129757

**Comment by devoncarew** [comment]
We should audit these packages for things like good readme content, std markdown headers for the packages, the pubspec descriptions, ...

**Comment by dcharkes** [comment]
> We should audit these packages for things like good readme content, std markdown headers for the packages, the pubspec descriptions, ...

Good point.

Also, we should probably publish `native_assets_builder` as [unlisted](https://github.com/dart-lang/pub-dev/issues/4044).
