### ISSUE TITLE
Java 9+ Modules support

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#730]
Java modules introduced in Java SE 9+ bring some layout changes which affect the assumptions we make with `doclet` backend.

For example, anything in `java.lang.*` belongs to `java.base` module. But if we use Android stubs, the layout is old layout which is not what the javadoc tool expects. So summarizer will fail with an error.

This also blocks dart-lang/native#761 - It's possible to use openjdk sources instead, but we prefer to use android source stubs because we want good interop with android and also license.

If someone wants to bind some java standard library classes, it's possible by passing `-m` option to summarizer. But it gets complex when you mix module and non-module classes in same project.

I want to design a better config and summarizer code than let the user solve this by passing arguments ad-hoc.

Note: ASM backend (`summarizer: backend: asm`) is not affected by this issue, since the module layout only affects source code.

Related: dart-lang/native#784

**Comment by HosseinYousefi** [comment]
Closing this as we intend to remove doclet (#1079).
