### ISSUE TITLE
Coherent sources for Android SDK core libraries

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#731]
Android SDK ships with some sources, notably platforms/android-$VERSION/android-stubs-src.jar and sources which can be downloaded through SDK manager.

But these sources are incomplete. There are missing classes. Javadoc fails on this kind of incomplete sources.

Until android SDK 28, stubs JAR used to be complete it seems.

Related: dart-lang/native#793 .

**Comment by HosseinYousefi** [comment]
Planning to remove doclet support (#1079), closing this.
