### ISSUE TITLE
Java standard library support

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#761]
We should also have a module which exports important parts of java stdlib, like collections API.

_Originally posted by @mahesh-hegde._

If we want to be able to pass objects between different generated bindings, we should make the generated bindings for the standard library reusable and put them in `package:jni`.

Probably blocked by:

* https://github.com/dart-lang/jnigen/issues/66

**Comment by HosseinYousefi** [comment]
Tracked in #746.
