### ISSUE TITLE
Support destroying JVM

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#768]
Current assumption is there will be one JNI in a process, and it exists until the end once spawned..

But there are cases where spawning and destroying JVM is desirable. Eg: in test runner, all test files' main() runs in same process, but the order is not deterministic. It would be good if each test group can independently spawn and destroy JVM.

Currently some parts of the C code assume that `jni.jvm` doesn't change once initialized. Refactoring those parts was harder than expected. Therefore leaving it as an issue.

**Comment by HosseinYousefi** [comment]
Not planned.
