### ISSUE TITLE
JavaDoc comment improvements.

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/native#789]
Current state:

* Split the javadoc comment obtained from API summary, do some primitive HTML tag replacement and write it as DartDoc.

Disadvantages:
* Reference to parameters etc.. will remain in javadoc syntax
* Not all HTML is replaced.

In future we might want to build a proper tree-like representation of the javadoc.

**Comment by HosseinYousefi** [comment]
Tracked in #1079.
