### ISSUE TITLE
[infra] Coverage issues

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#812]
Now that we have added coverage from multiple workflows, Coveralls is forgetting the coverage from other workflows.
<img width="108" alt="image" src="https://github.com/dart-lang/native/assets/3601775/2f81e4c8-45ad-41f4-b8f0-472565c37150">

FFIgen CI ran last:
<img width="184" alt="image" src="https://github.com/dart-lang/native/assets/3601775/e0583293-be8e-4534-9b9c-59c4a0fab1d5">

This is a reintroduction of https://github.com/dart-lang/native/issues/10:

> It combines coverage from jobs from a single workflow but not jobs from separate workflows.

Secondly, Coveralls doesn't seem to find the source file locations:
<img width="472" alt="image" src="https://github.com/dart-lang/native/assets/3601775/90f1de3f-4bce-4525-87f8-523517e70c56">

We should either see if we can fix the setup for Coveralls, or switch to CodeCov (https://github.com/dart-lang/native/issues/70#issuecomment-1610097510).

cc @HosseinYousefi @liamappelbe

**Comment by HosseinYousefi** [comment]
The source not available problem might be because you have not signed in?

**Comment by dcharkes** [comment]
> The source not available problem might be because you have not signed in?

Thanks!

I wonder why one needs to be signed in to see the source code of a public repo? 🤔

**Comment by HosseinYousefi** [comment]
> I wonder why one needs to be signed in to see the source code of a public repo? 🤔

I had wondered the same before! Btw the PR doesn't seem to work, I also pushed some code to trigger jnigen's CI as well, but coverall still only shows ffigen's coverage.

**Comment by dcharkes** [comment]
The flag name seems to be ignored for ffigen: https://coveralls.io/builds/64057741
But then works fine for jnigen: https://coveralls.io/builds/64057335

The only difference I can see is `parallel: true` and then a separate call to finish the coverage. That should not influence it.

**Comment by dcharkes** [comment]
It looks like coverage is now working as expected: https://github.com/dart-lang/native/pull/819#issuecomment-1820441128
