### ISSUE TITLE
Auto generate a compatibility layer when `ffi-native` is enabled, such that users using the old DynalicLibrary way can seamlessly integrate with it

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/native#821]
Hi thanks for the ffigen tool! I am considering using the ffi-native way for https://github.com/fzyzcjy/flutter_rust_bridge. However, I need to support both ffi-native and the old DynamicLibrary way (at least now) because it is under experimental flag, so there must exist many users who do not want to use in production yet for the new way. It is OK for me to generate a compatibility layer (i.e. a class whose methods call the new ffi-native functions), but there is another consideration:

When ffi-native is stable, I guess many people will want to switch to it, because it is faster (when isLeaf=true). But currently, the generated APIs are not compatible - the old way is an instance method, while the new way is a file-level function. Therefore, anyone who wants to switch will have to migrate all their code, which is a bit of work.

Therefore, I guess it would be great to provide a compatibility layer, which simply mimics the old class-based API, and forwards everything to the new `@Native` functions. P.S. If we use vm:prefer-inline pragma, we may not lose any performance, so the performance is not an issue.

**Comment by dcharkes** [comment]
If you use the new API as a named import named as what the instance was named, then you should be able to not change the rest of the code.

Or would you like your users to be able to switch at runtime? E.g. you can swap the old instance out for the new one based on a boolean? I don't believe that that would work, because you'd still need a `build.dart`, which would then prevent your package from being used without the experiment enabled.

**Comment by fzyzcjy** [comment]
Thank you for the information!

> Could you share a bit more on how you'd like to use this compatibility layer?

As for me (flutter_rust_bridge), I want the same (FRB generated) code can use the new and old ffigen outputs. But that is not strongly needed, since I can let FRB generate the layer.

For users, the "named import" solution looks great! Just one nit: it may not be easily mockable unlike the old one, for example, if someone wants to mock the API calls to Rust using mockito (or whatever package).

**Comment by dcharkes** [comment]
> As for me (flutter_rust_bridge), I want the same (FRB generated) code can use the new and old ffigen outputs. But that is not strongly needed, since I can let FRB generate the layer. 

Do I understand correctly that the users of FRB configure FRB to generate one or the other, and then commit generated code to their package? (E.g. exactly how users of FFIgen configure it.) Which means that the package author decided whether to depend on the experimental native assets feature or not.

Yeah, if your code generator just generates the object or the named import that would solve it.

I think we might then close this issue as wont fix / not planned.

> it may not be easily mockable unlike the old one, for example, if someone wants to mock the API calls to Rust using mockito (or whatever package).

I think we've settled on the idea that we either (1) write a layer around `dart:ffi` bindings and mock that layer, or (2) write integration tests that actually use the native code. See discussion in https://github.com/dart-lang/sdk/issues/53980.

**Comment by fzyzcjy** [comment]
> Do I understand correctly that the users of FRB configure FRB to generate one or the other, and then commit generated code to their package? (E.g. exactly how users of FFIgen configure it.) Which means that the package author decided whether to depend on the experimental native assets feature or not.

Yes, sth like that.

> I think we've settled on the idea that we either (1) write a layer around dart:ffi bindings and mock that layer, or (2) write integration tests that actually use the native code. See discussion in https://github.com/dart-lang/sdk/issues/53980.

Looks reasonable!

> I think we might then close this issue as wont fix / not planned.

Sure :)
