### ISSUE TITLE
When executing a third-party binary, the `build.dart` is also executed, causing some trouble

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/native#822]
Hi thanks for the Dart language and ecosystem! When working on the https://github.com/dart-lang/sdk/issues/50565 native assets, I have some problem as follows. 

For simplicity, suppose we are working on the example https://github.com/dart-lang/native/tree/main/pkgs/native_assets_cli/example (indeed I am working on flutter_rust_bridge v2). As https://pub.dev/packages/ffigen suggests, to use ffigen, I should invoke `dart run ffigen` command. However, I find that dart automatically executes `build.dart` when doing `dart run ffigen`, even though we know executing `ffigen` do not need to compile things mentioned in build.dart.

Thus, I hope that, when doing `dart run ffigen`, we do not run `build.dart` at all.

P.S. Why it is an issue in my case: `build.dart` triggers compilation of the C code in the analogy example above (indeed Rust code in flutter_rust_bridge). However, the C code (indeed rust code) can temporarily fail to compile (because it is auto-generated in flutter_rust_bridge), while I do want ffigen to succeed in running.

Workaround: I can install ffigen as a *global* dart package and run it. However, that does not sound very elegant because, e.g, we will be polluting the global namespace of the user, then it is hard for the user to use two ffigen versions, etc.

**Comment by fzyzcjy** [comment]
Thank you for the reply, and looking forward to the P1 fix! (Not sure why github does not give any notification of this message...)

**Comment by dcharkes** [comment]
This has unintended consequences for `dart run test`. `dart test` would work as expected, but `dart run test` would not build any native assets, just like how `dart run ffigen` would not build any native assets.

**Comment by fzyzcjy** [comment]
Firstly I also believe everyone is using `dart test` :) Secondly, if `dart run test` somehow *compiles* the code in the package, I guess that compilation of Dart should be enough to trigger build.dart?

**Comment by dcharkes** [comment]
> Secondly, if `dart run test` somehow _compiles_ the code in the package, I guess that compilation of Dart should be enough to trigger build.dart?

It is not, it's a manual invocation of kernel compilation. The kernel file is just output somewhere on the file system. And then package test `spawnUri`s that kernel file. So it bypasses all `package:dartdev`'s logic.

I'll just add a small workaround in https://dart-review.googlesource.com/c/sdk/+/339124/4/pkg/dartdev/lib/src/commands/run.dart in case anyone was using it.

**Comment by dcharkes** [comment]
Heh, expect my amazement when reverse engineering all of that earlier to make native assets work. 😆

**Comment by fzyzcjy** [comment]
Looking forward to the next release!
