### ISSUE TITLE
[native_assets_builder] Rename `build.dart` to `hook/build.dart`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#823]
We have settled on `hook/build.dart` as the place for the `build.dart` "script"/"hook".

* https://github.com/dart-lang/sdk/issues/54334

If we fall back to `build.dart` for the time being, we have less rolling issues.

The example that's run against the Dart SDK will break for the time being though.

* [x] Update `native_assets_builder` to look for `hook/build.dart` instead of `build.dart`. For now: fall-back to `build.dart` if `hook/build.dart` does not exist, to not immediately break everyone.
* [x] Update tests.
* [x] Update "script" terminology to "hook".
* [x] Roll into Dart.
* [x] Update examples (requires Dart roll).
* [x] Roll into Flutter. (currently blocked by https://github.com/dart-lang/native/issues/1049)

**Comment by dcharkes** [comment]
It will be easier to roll stuff if we first land `build_assets.dart` to preceed `build.dart` roll everything, and then remove `build.dart`.

**Comment by dcharkes** [comment]
Note from offline discussion: We might want to stick with `build.dart`. So far we have only a single conflicting use: https://github.com/flutter/flutter/issues/138727#issuecomment-1827568913.

**Comment by mit-mit** [comment]
I still prefer the more general names. We may only know of a single conflict now, but having a hard coded name is a very brute mechanism, so I think it should be more specific.

**Comment by dcharkes** [comment]
* [ ] Update `native_assets_builder` to look for `hook/build.dart` instead of `build.dart`. For now: fall-back to `build.dart` if `hook/build.dart` does not exist, to not immediately break everyone.
* [ ] Update examples / tests.
* [ ] Update "script" terminology to "hook".
* [ ] Roll into Dart.
* [ ] Roll into Flutter.

**Comment by dcharkes** [comment]
With renaming script to hook. The question is, is the `hook/build.dart` itself the hook? Or is the thing that invokes the `hook/build.dart` the hook? It could be argued either way. 🙈 

Since `build.dart` is placed inside `hook/` (and not inside `hooked/` 😆 ), I'm leaning towards the `hook/build.dart` being called a hook. And the thing that invokes the hook to be the "invoker", or "to latch on", or something.

So I'm going to call a package's `hook/build.dart` that packages "build hook".

Ready for another round of bike shedding! cc @mosuem

**Comment by dcharkes** [comment]
This has rolled into Flutter in:

* https://github.com/flutter/flutter/pull/145612
