### ISSUE TITLE
How to get a function pointer for `NativeFinalizer` when using `@Native` mode?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/native#826]
Hi thanks for the Dart language! I need to use NativeFinalizer https://api.dart.dev/stable/3.2.1/dart-ffi/NativeFinalizer-class.html (in flutter_rust_bridge), but I am not sure how to provide a pointer for it.

As we know, the plain old way (e.g. shown in the link above) is to do a DynamicLibrary.lookup to find the address. However, if we use the new ffi-native mode of ffigen, we will get `@Native external` functions, thus cannot find any addresses.

I did see https://api.dart.dev/stable/3.2.1/dart-ffi/Pointer/fromFunction.html, but since https://api.dart.dev/stable/3.2.1/dart-ffi/NativeFinalizer/NativeFinalizer.html says "an FFI trampoline (a function pointer obtained via Pointer.fromFunction) is not supported", so I guess it is not useful.

**Comment by dcharkes** [comment]
@fzyzcjy You're not the first one asking for this, we're already working on it!

This is tracked in:

* https://github.com/dart-lang/sdk/issues/50552

And a PR in:

* https://dart-review.googlesource.com/c/sdk/+/333920

Once we have `addressOf`, we might not need anything in FFIgen, as FFIgen generates `@Native`s directly.

**Comment by fzyzcjy** [comment]
Looking forward to it, thank you!

(Closing as duplicate)
