### ISSUE TITLE
[Objective-C interop] Invalid argument(s): Failed to lookup symbol 'objc_msgSend_fpret'

### ISSUE THREAD

**Issue by LastMonopoly** [dart-lang/native#829]
Hi all,

https://github.com/dart-lang/native/tree/main/pkgs/ffigen/example/objective_c
the above example no longer works when I generate bindings myself using `dart run ffigen --config config.yaml`

when I `dart play_audio.dart test.mp3`, the exception throws
> Invalid argument(s): Failed to lookup symbol 'objc_msgSend_fpret': dlsym(0x3c28dd4a8, objc_msgSend_fpret): symbol not found

This is my flutter version
```
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-CN)
    • Flutter version 3.16.0 on channel stable at /Users/xhan/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (11 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/xhan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/xhan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3
```

This is the newly generated binding
[avf_audio_bindings.dart.zip](https://github.com/dart-lang/native/files/13466401/avf_audio_bindings.dart.zip)

Thanks.

**Comment by dcharkes** [comment]
I can repro this on https://github.com/dart-lang/native/commit/0051e78df8a310ee6cbaf0feffac8e804554ee9a.


```
00:04 +68 -6: test/native_objc_test/block_test.dart: Blocks Struct block [E]                                                                                                                                                                                      
  Invalid argument(s): Failed to lookup symbol 'objc_msgSend_stret': dlsym(0x8bfb4b30, objc_msgSend_stret): symbol not found
  dart:ffi                                           DynamicLibrary.lookup
```

Maybe this comment was not correct: https://github.com/dart-lang/native/issues/449#issuecomment-1813396612

I don't find much googling around on fpret and stret and Apple silicon, but we don't seem to be the only ones having the issue: https://www.google.com/search?q=objc_msgSend_stret+not+found+arm64

**Comment by dcharkes** [comment]
@liamappelbe can you make a PR that branches based on `Abi.current`?

I believe we should also be able to test this on CI now: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
