### ISSUE TITLE
In jnigen, Java objects seem to be auto managed by Dart heap, is it allowed, or shall we call `dispose` manually for each object?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/native#848]
Cross-post from https://github.com/dart-lang/sdk/issues/54233, since if we should not do this, the jnigen may need some refactor. (I hope we are allowed to do such auto management!)

**Comment by HosseinYousefi** [comment]
By default Java objects (classes extending `JObject`) are attached to a `NativeFinalizer`, so once they're unreachable and GC runs, `DeleteGlobalRef` is called. 

Alternatively you can delete the global reference manually by calling `.release()`:

```dart
final o = someJObject();
// do stuff with o
o.release();
```
or using an `Arena`:

```dart
using((arena) {
  final o = someJObject()..releasedBy(arena);
});
// o is released here.
```

`release` internally detaches the native finalizer, and calls the `DeleteGlobalRef` immediately. 

This doesn't mean that the object is completely GC'd though. Only this one global reference to the object is released. Once the object is unreachable completely (no references in either Java or global references in Dart), JVM will eventually GC it.

**Comment by fzyzcjy** [comment]
Thank you for the info, I know it is done by native finalizer, and my main worry was described in https://github.com/dart-lang/sdk/issues/54233.

**Comment by HosseinYousefi** [comment]
> Thank you for the info, I know it is done by native finalizer, and my main worry was described in [dart-lang/sdk#54233](https://github.com/dart-lang/sdk/issues/54233).

JNIgen solves this by giving the option of manually releasing the references to the user. Small number of small objects? Fine to let it be cleaned up by the GC. Large number of objects? Maybe use an arena to explicitly clean up the references (and still rely on JVM to clean up the object in its own GC cycle – since there isn't really an explicit `dispose` in Java). 

Java is also different from Rust with the memory ownership rules and not having a GC. So the exact same approach might not be applicable to your package.

**Comment by dcharkes** [comment]
> Java is also different from Rust with the memory ownership rules and not having a GC. So the exact same approach might not be applicable to your package.

+1 https://github.com/dart-lang/native/issues/849#issuecomment-1840736268

> JNIgen solves this by giving the option of manually releasing the references to the user. Small number of small objects? Fine to let it be cleaned up by the GC. Large number of objects? Maybe use an arena to explicitly clean up the references (and still rely on JVM to clean up the object in its own GC cycle – since there isn't really an explicit `dispose` in Java).

If users of JNIgen are in a context where there is already a dispose cycle (e.g. some Flutter code), you can hook into that.

Organizing flutter_rust_bridge in the same way (e.g. attaching a native finalizer, and cancelling the native finalizer on a manual `dispose` call) gives your users the option based on usage pattern.
