### ISSUE TITLE
[c_compiler] package name

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#85]
> "Package name c_compiler is too similar to another active package: ccompilers (https://pub.dev/packages/ccompilers)."

We can't use `package:c_compiler` as a package name.

ccompilers is an outdated package which hasn't been touched for 4 years.

The reason we went for `c_compiler` is that we could have a `rust_compiler` package etc.

Suggestion by @jonasfj: `native_toolchain_c`.

The upside of that name is it has 'native' which makes it fit with the other native packages in this repo.
The downside is that the package name is considerably longer.

Blocks:

* https://github.com/dart-lang/native/issues/71

@devoncarew @mit-mit @HosseinYousefi any opinions?

**Comment by dcharkes** [comment]
@mezoni The `package:ccompilers` used to be on https://github.com/mezoni/ccompilers according to the last published version, but that repository has been deleted or made private. Do you have any intention of maintaining this package? If no, would you consider [discontinuing](https://dart.dev/tools/pub/publishing#discontinue) it?

**Comment by dcharkes** [comment]
For reference: Rust calls it's C compiler wrapper package `cc` https://docs.rs/cc/latest/cc/.


Some more notes dug up somewhere from @devoncarew and me:

> Maybe this should be c_compiler, so that other packages can be named rust_compiler, cplusplus_compiler etc.
> 
> Or maybe c_builder, because it builds C code using a c compiler, but is not a c compiler itself. (And then rust_builder)
> 
> Or, maybe c_assets_builder, to connect the name with "native_assets".

> Perhaps this could be the abstract impl. of a compiler - w/ utilities to parse the CLI standard, some tool locating utilities, and process management. We could ship a separate package which was the clang impl. of the above; so:
> - package:cc is the abstraction - the compiler agnostic package
> - package:cc_clang is one implementation of the above, based on clang
> Generally, I like having a unifying prefix for these packages; the base package, and the other compiler packages that will exists, either that we ourselves ship (clang) or that the community will ship (rust, ...). That could be 'cc_' or some other prefix.

`package:native_toolchain_XXX` does create a unifying prefix.

**Comment by dcharkes** [comment]
@devoncarew I can't make new labels in this package or rename the existing label `package:c_compiler` label.

**Comment by devoncarew** [comment]
> @devoncarew I can't make new labels in this package or rename the existing label `package:c_compiler` label.

You should have more than sufficient permissions to (an repo committer can modify labels).

**Comment by dcharkes** [comment]
> > @devoncarew I can't make new labels in this package or rename the existing label `package:c_compiler` label.
> 
> You should have more than sufficient permissions to (an repo committer can modify labels).

Ah, it's not in the "settings" part. Done.
