### ISSUE TITLE
[ffigen] `symbol-address` with `@Native`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#852]
Now that we landed https://github.com/dart-lang/sdk/commit/a44a524bb099ad8c3a87aaf6614a752f1a025a6e, we can start supporting `symbol-address` for functions.

And once https://github.com/dart-lang/sdk/issues/50551 is addressed, we can add fields and the addresses of fields.

**Comment by parlough** [comment]
@simolus3 Is really going full speed ahead 💙
