### ISSUE TITLE
iOS plugin with debug and release variant of a .framework

### ISSUE THREAD

**Issue by vaind** [dart-lang/native#900]
I have a plugin (let's say it's named `plugin`) that needs to have a separate debug build (say `debug/foo.framework`) and a release build (`release/foo.framework`) and they should be used in the respective app builds. Is there a way to do this? Ideally, on the plugin's side but if necessary even some changes to the app config would be acceptable. 

The closest thing I've found is this: `pod 'Lookback', :configurations => ['Debug']` (https://blog.cocoapods.org/CocoaPods-0.34/) but not sure if/how that's usable.

Here's the current .podspec but I need to manually replace the foo.framework with the variant I want used with the current flutter run/build. 

```podspec
Pod::Spec.new do |s|
  s.name             = 'plugin'
  s.version          = '0.0.1'
  s.license          = { :file => '../LICENSE' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'Flutter'
  s.platform = :ios, '8.0'
  s.xcconfig = {
        'HEADER_SEARCH_PATHS' => [
            '"${PODS_TARGET_SRCROOT}"'
        ],
  }
  s.preserve_paths = 'foo.framework'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-framework foo' }
  s.vendored_frameworks = 'foo.framework'
  # Flutter.framework does not contain a i386 slice.
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.swift_version = '5.0'
end
```

**Comment by dcharkes** [comment]
Hopefully this is solved with the native assets feature.
