### ISSUE TITLE
Add NativeFinalizer to go with malloc and calloc

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#910]
Our malloc and calloc allocators use a different allocator on Windows.

This means that devs wanting to use a `NativeFinalizer` with `malloc` and `calloc` need to branch on OS.

Also, devs wanting to use `NativeFinalizer`s with `malloc` and `calloc` rely on the specific memory allocator that `package:ffi` uses under the hood. This means we cannot change the underlying allocator without breaking dependencies.

If we would provide a `NativeFinalizer` that would free the memory backed by calloc and malloc, we could change the implementation without breaking people. (Assuming they do not lookup their own "free" somewhere.)

cc @timsneath heads up for package:win32
cc @mkustermann we're locked in to CoTaskMemAlloc

**Comment by mkustermann** [comment]
As suggested above, the package has now a `Allocator.nativeFree` that can be used in finalizers (see https://github.com/dart-lang/ffi/pull/203). I think this should close this issue, right?
