### ISSUE TITLE
[native_assets_cli] We cannot ever do breaking changes to the programmatic API

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#950]
If many packages start depending on this helper package, bumping the major version is going to be a no go. Some examples of packages which are at 1.something forever: https://pub.dev/packages/collection, https://pub.dev/packages/meta (and probably https://pub.dev/packages/ffi at 2.something forever).

This means we need to come up with a workflow that does allow evolution of the programmatic API:

We could do `package:native_assets_cli/v1.dart` and rev that version number every time we want to do a breaking change. We keep the old version working, but mark it deprecated and hide the API docs.

We should also have a workflow for experiments that does not unnecessarily bump the major version:

We could have a `package:native_assets_cli_experiments` which is a copy of the latest version of `native_assets_cli`. @mosuem This would enable us to merge WIP on `LinkConfig`/`LinkOutput` while the data assets feature is experimental but the native assets feature is already out of experimental. WDYT? Any better ideas?

Thanks @jonasfj for suggesting a bunch of options.

**Comment by mosuem** [comment]
Alternatively, we can just use semver as usual. If my package then decides to switch to `2.0.0`, I can't use other packages with dependency on `^1.0.0` until they upgrade. This is the same way we handle other dependencies - if a package today would have an SDK dependency on `<3.0.0`, then it would be unusable for any Dart 3 project.

**Comment by dcharkes** [comment]
> Alternatively, we can just use semver as usual. If my package then decides to switch to `2.0.0`, I can't use other packages with dependency on `^1.0.0` until they upgrade. This is the same way we handle other dependencies - if a package today would have an SDK dependency on `<3.0.0`, then it would be unusable for any Dart 3 project.

Then no-one can use the new version of package until all the other packages in the ecosystem (which happen to be used together with your package) have switched to `2.0.0`, which means none of the features you release afterwards will be available to your users for some time.
