### ISSUE TITLE
jnigen problem when running command

### ISSUE THREAD

**Issue by AuraCodez** [dart-lang/native#954]
hello, when i run dart run jnigen --config jnigen.yaml in my app, it keeps saying gradle exited with status 1, this can be because the android build is not yet cached. Please run 'flutter build apk' in ./ and try again. I run that and i still get that problem. Its because of android_sdk_config: add_gradle_deps: true if I remove that it works but i want it to compile the androidx library to how can I fix this??

**Comment by HosseinYousefi** [comment]
Running `flutter build apk` should work, the same mechanism is used in the [pedometer example](https://github.com/flutter/samples/tree/main/experimental/pedometer). Can you try cloning the pedometer example and see if that works or not? Since that's also used to generate bindings for `androidx.health.connect` library.

**Comment by AuraCodez** [comment]
> Running `flutter build apk` should work, the same mechanism is used in the [pedometer example](https://github.com/flutter/samples/tree/main/experimental/pedometer#jnigen). Can you try cloning the pedometer example and see if that works or not? Since that's also used to generate bindings for `androidx.health.connect` library.

ok so i cloned the project and ran dart run jnigen --config jnigen.yaml and  it generated the bindings correctly

**Comment by AuraCodez** [comment]
i see in the classes you added the androidx stuff, i didnt do that i will just try to copy your jnigen.yaml file

**Comment by AuraCodez** [comment]
@HosseinYousefi So I am confused about the directory in the pedometer, did you use flutter add to app feature? Basically I am using flutter add to app and I put in the jnigen.yaml file in the flutter module folder and also the pubspec.yaml file. I don't know why I can generate bindings for the pedometer example and not my app.

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi So I am confused about the directory in the pedometer, did you use flutter add to app feature? Basically I am using flutter add to app and I put in the jnigen.yaml file in the flutter module folder and also the pubspec.yaml file. The flutter module folder is in the directory of my android app. I don't know why I can generate bindings for the pedometer example and not my app.

I can't know for sure, until you provide me with a reproducible example. Pedometer is not using add to app.

That said, if the bindings generation works a certain way, like in a separate package (pedometer), you can use that to get the bindings generated in the mean time.

**Comment by AuraCodez** [comment]
So my class has imports from other classes, will it still be able to generate the bindings? It seems to not found the imports saying error can not found symbol.

**Comment by AuraCodez** [comment]
Thanks for the help, I faced another issue  in which I will make another thread soon
