### ISSUE TITLE
Either hide or heavily discourage the use of `reference` and `fromRef`

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/native#979]
Although safe methods like `castTo` are provided, users might still use `fromRef` and `.reference` to manually cast objects (see #970), keep references without properly managing their lifecycle, etc. Therefore, JniGen generated code should heavily discourage the use of these inner workings and eventually hide them. Right now, we need references to send these finalizable `JObject`s between multiple isolates, but https://github.com/dart-lang/sdk/issues/55062 will make these objects sendable.

cc/ @dcharkes

**Comment by yanshouwang** [comment]
Hello, @HosseinYousefi
I found here you mentioned that we can send JObject between isolates, but when I send the reference to another isolate and call formRef constructor, the first time it's ok to do this, but when I send this reference again, the fromRef method will throw error like this:
```
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jobject is an invalid global reference: 0x357a (deleted reference at index 427)
```
Is it possible for us to send JObject to another isolate?

**Comment by HosseinYousefi** [comment]
I have explained one way to send them here: https://github.com/dart-lang/native/issues/970#issuecomment-1980477374

**Comment by yanshouwang** [comment]
@HosseinYousefi
Thank you for your answer, that's works like a charm~

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi Thank you for your answer, that's works like a charm~

With the newly released 0.8.0, you can skip the manual way (in Dart's main branch – not yet in stable) and just pass `JObject`s around as you would with any other object.

**Comment by yanshouwang** [comment]
> With the newly released 0.8.0, you can skip the manual way (in Dart's main branch – not yet in stable) and just pass `JObject`s around as you would with any other object.

@HosseinYousefi , I have update to 0.8.0, when I pass the JObject to an isolate, the error throws, I use the flutter stable channel now.

``` Bash
E/flutter (13009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object is a Pointer)
E/flutter (13009):  <- Instance of 'JGlobalReference' (from package:jni/src/jreference.dart)
E/flutter (13009):  <- $type in Instance of 'BarcodeScanner' (from package:hybrid_vision_android/src/jni.g.dart)
E/flutter (13009):  <- scanner in Instance of '_DetectCommand' (from package:hybrid_vision_android/src/barcode_detection.dart)
E/flutter (13009): 
E/flutter (13009): #0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:250:43)
E/flutter (13009): #1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:231:5)
E/flutter (13009): #2      AndroidBarcodeDetector.detect (package:hybrid_vision_android/src/barcode_detection.dart:51:14)
E/flutter (13009): <asynchronous suspension>
E/flutter (13009): #3      _BarcodeDetectionViewState.buildDetectView.<anonymous closure>.<anonymous closure> (package:hybrid_vision_android_example/views/barcode_detection_view.dart:173:38)
E/flutter (13009): <asynchronous suspension>
E/flutter (13009): 
```

**Comment by HosseinYousefi** [comment]
> > With the newly released 0.8.0, you can skip the manual way (in Dart's main branch – not yet in stable) and just pass `JObject`s around as you would with any other object.
> 
> @HosseinYousefi , I have updated to 0.8.0, when I pass the JObject to an isolate, the error throws, I use the flutter stable channel now.
> 
> ```shell
> E/flutter (13009): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object is a Pointer)
> E/flutter (13009):  <- Instance of 'JGlobalReference' (from package:jni/src/jreference.dart)
> E/flutter (13009):  <- $type in Instance of 'BarcodeScanner' (from package:hybrid_vision_android/src/jni.g.dart)
> E/flutter (13009):  <- scanner in Instance of '_DetectCommand' (from package:hybrid_vision_android/src/barcode_detection.dart)
> E/flutter (13009): 
> E/flutter (13009): #0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:250:43)
> E/flutter (13009): #1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:231:5)
> E/flutter (13009): #2      AndroidBarcodeDetector.detect (package:hybrid_vision_android/src/barcode_detection.dart:51:14)
> E/flutter (13009): <asynchronous suspension>
> E/flutter (13009): #3      _BarcodeDetectionViewState.buildDetectView.<anonymous closure>.<anonymous closure> (package:hybrid_vision_android_example/views/barcode_detection_view.dart:173:38)
> E/flutter (13009): <asynchronous suspension>
> E/flutter (13009): 
> ```

As I said, it's not available on stable channel yet. Use the main channel.

**Comment by yanshouwang** [comment]
> As I said, it's not available on stable channel yet. Use the main channel.

Is there a exact Dart version that I can do this on stable channel?

**Comment by HosseinYousefi** [comment]
> Is there a exact Dart version that I can do this on stable channel?

@dcharkes In which version will `@pragma('vm:deeply-immutable')` land?

**Comment by yanshouwang** [comment]
Thanks, I'll wait for this feature, Can I use the `JGlobalReference` to do the manual steps like before?

**Comment by HosseinYousefi** [comment]
> Thanks, I'll wait for this feature, Can I use the `JGlobalReference` to do the manual steps like before?

Yes, you can.

**Comment by HosseinYousefi** [comment]
Not currently planned as we still need `reference` for certain `Jni.env` functionalities that don't exist in a nicer way.
