### ISSUE TITLE
[native_assets_cli] In non-dry-run no assets with a different arch or OS should be ignored

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/native#989]
The native assets builder was silently trying to include the assets from the wrong architecture.

We should either be ignoring them or giving errors about it.

Example fix: https://github.com/google/flutter-mediapipe/pull/20/commits/ce83c3a5dd160d0501f1433123eb6d6c77f325f8

cc @craiglabenz

**Comment by blaugold** [comment]
Looks like this is already being validated now:

https://github.com/dart-lang/native/blob/23a42e032d9cbe2347cd47546b14839e2b01bad6/pkgs/native_assets_cli/lib/src/code_assets/validation.dart#L191-L194

**Comment by dcharkes** [comment]
Thanks @mkustermann!
