### ISSUE TITLE
How to convert JArray<jbyte> to Uint8List efficiently?

### ISSUE THREAD

**Issue by yanshouwang** [dart-lang/native#990]
When convert Uint8List to JArray<jbyte>, we can use the `JArray<jbyte>.setRange` extension method.
But I don't know how to do the opposite way.
Currently I can do this by use a for-loop, but I think this will spend a lot when convert a large byte array.

**Comment by mkustermann** [comment]
Right now we have [JArray](https://github.com/dart-lang/native/blob/3555b62284a4f10391/pkgs/jni/lib/src/jarray.dart#L112):
```dart
class JArray<E> extends JObject { ... }
extension ByteArray on JArray<jbyte> {
  int operator [](int index) {
    return elementAt(index, JniCallType.byteType).byte;
  }

  void operator []=(int index, int value) {
    RangeError.checkValidIndex(index, this);
    _allocate<JByteMarker>(sizeOf<JByteMarker>(), (ptr) {
      ptr.value = value;
      Jni.env.SetByteArrayRegion(reference.pointer, index, 1, ptr);
    });
  }

  void setRange(int start, int end, Iterable<int> iterable,
      [int skipCount = 0]) {
      ...
      Jni.env.SetByteArrayRegion(reference.pointer, start, size, ptr);
  }
}
```

Maybe this just needs a
```dart
void getRange(int start, int end, Uint8List output) { ... }
// or 
Uint8List getRange(int start, int end) { ... }
```
that is then implemented via `Jni.env.GetByteArrayRegion` to get C pointers to memory and then copy it to a dart typed list.

**Comment by HosseinYousefi** [comment]
> When convert Uint8List to JArray, we can use the `JArray<jbyte>.setRange` extension method. But I don't know how to do the opposite way. Currently I can do this by use a for-loop, but I think this will spend a lot when convert a large byte array.

What @mkustermann said can be done, alternatively you can do

```dart
JByteBuffer.wrap(array).asUint8List(releaseOriginal: true);
```

**Comment by HosseinYousefi** [comment]
What @mkustermann said is possible. We can support the `getRange` operation as well.

I first wrote something wrong about using `JByteBuffer`s, that's not currently possible, because we can only convert direct `JByteBuffer`s into `Uint8List`s. 

---

If you don't have to use an array, you can use `JByteBuffer` directly, maybe that simplifies your code.

```dart
final buffer = JByteBuffer.fromList(list);
final list = buffer.asUint8List();
```

**Comment by yanshouwang** [comment]
> What @mkustermann said is possible. We can support the `getRange` operation as well.
> 
> I first wrote something wrong about using `JByteBuffer`s, that's not currently possible, because we can only convert direct `JByteBuffer`s into `Uint8List`s.
> 
> If you don't have to use an array, you can use `JByteBuffer` directly, maybe that simplifies your code.
> 
> ```dart
> final buffer = JByteBuffer.fromList(list);
> final list = buffer.asUint8List();
> ```

The JByteArray is returned by a Kotlin method, so I can't use JByteBuffer instead, I think provide a `getRange` extension will be nice.
